queue_rules:
  - name: default
    checks_timeout: 2 h
    branch_protection_injection_mode: queue
    merge_method: squash
    conditions:
      - base=main
      - label=ci:ready_to_merge
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body_raw  }}
    
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
      - label=ci:ready_to_merge
    actions:
      queue:
        name: default

  - name: remove ci:ready_to_merge label
    conditions:
      - merged
    actions:
      label:
        remove:
          - ci:ready_to_merge
