# Description:
#   Test data for the signal library

package(
    default_visibility = ["//signal:__subpackages__"],
    licenses = ["notice"],
)

exports_files([
    "rfft_test1.txt",
    "window_test1.txt",
])
