# Description:
#   Test data for the signal library

package(
    default_visibility = ["//signal:__subpackages__"],
    licenses = ["notice"],
)

exports_files([
    "energy_test1.txt",
    "fft_auto_scale_test1.txt",
    "filter_bank_accumulation_8k.txt",
    "filter_bank_accumulation_16k.txt",
    "filter_bank_accumulation_44k.txt",
    "filter_bank_test1.txt",
    "filter_bank_square_root_test1.txt",
    "filter_bank_spectral_subtraction_test1.txt",
    "framer_test1.txt",
    "pcan_op_test1.txt",
    "rfft_test1.txt",
    "stacker_test1.txt",
    "window_test1.txt",
])
