# Description:
#   generated integration test for one specific kernel in a model.
load(
    "//tensorflow/lite/micro:build_def.bzl",
    "generate_cc_arrays",
    "tflm_cc_library",
    "tflm_cc_test",
)

package(
    default_visibility = ["//visibility:public"],
    # Disabling layering_check because of http://b/177257332
    features = ["-layering_check"],
    licenses = ["notice"],
)

generate_cc_arrays(
    name = "generated_conv0_model_data_cc",
    src = "conv0.tflite",
    out = "conv0_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv0_model_data_hdr",
    src = "conv0.tflite",
    out = "conv0_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv1_model_data_cc",
    src = "conv1.tflite",
    out = "conv1_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv1_model_data_hdr",
    src = "conv1.tflite",
    out = "conv1_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv2_model_data_cc",
    src = "conv2.tflite",
    out = "conv2_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv2_model_data_hdr",
    src = "conv2.tflite",
    out = "conv2_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv3_model_data_cc",
    src = "conv3.tflite",
    out = "conv3_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv3_model_data_hdr",
    src = "conv3.tflite",
    out = "conv3_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv4_model_data_cc",
    src = "conv4.tflite",
    out = "conv4_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv4_model_data_hdr",
    src = "conv4.tflite",
    out = "conv4_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv5_model_data_cc",
    src = "conv5.tflite",
    out = "conv5_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv5_model_data_hdr",
    src = "conv5.tflite",
    out = "conv5_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv6_model_data_cc",
    src = "conv6.tflite",
    out = "conv6_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv6_model_data_hdr",
    src = "conv6.tflite",
    out = "conv6_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv7_model_data_cc",
    src = "conv7.tflite",
    out = "conv7_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv7_model_data_hdr",
    src = "conv7.tflite",
    out = "conv7_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv8_model_data_cc",
    src = "conv8.tflite",
    out = "conv8_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv8_model_data_hdr",
    src = "conv8.tflite",
    out = "conv8_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv9_model_data_cc",
    src = "conv9.tflite",
    out = "conv9_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv9_model_data_hdr",
    src = "conv9.tflite",
    out = "conv9_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv10_model_data_cc",
    src = "conv10.tflite",
    out = "conv10_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv10_model_data_hdr",
    src = "conv10.tflite",
    out = "conv10_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv11_model_data_cc",
    src = "conv11.tflite",
    out = "conv11_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv11_model_data_hdr",
    src = "conv11.tflite",
    out = "conv11_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv12_model_data_cc",
    src = "conv12.tflite",
    out = "conv12_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv12_model_data_hdr",
    src = "conv12.tflite",
    out = "conv12_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv13_model_data_cc",
    src = "conv13.tflite",
    out = "conv13_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv13_model_data_hdr",
    src = "conv13.tflite",
    out = "conv13_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv14_model_data_cc",
    src = "conv14.tflite",
    out = "conv14_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv14_model_data_hdr",
    src = "conv14.tflite",
    out = "conv14_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv15_model_data_cc",
    src = "conv15.tflite",
    out = "conv15_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv15_model_data_hdr",
    src = "conv15.tflite",
    out = "conv15_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv16_model_data_cc",
    src = "conv16.tflite",
    out = "conv16_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv16_model_data_hdr",
    src = "conv16.tflite",
    out = "conv16_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv17_model_data_cc",
    src = "conv17.tflite",
    out = "conv17_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv17_model_data_hdr",
    src = "conv17.tflite",
    out = "conv17_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv18_model_data_cc",
    src = "conv18.tflite",
    out = "conv18_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv18_model_data_hdr",
    src = "conv18.tflite",
    out = "conv18_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv19_model_data_cc",
    src = "conv19.tflite",
    out = "conv19_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv19_model_data_hdr",
    src = "conv19.tflite",
    out = "conv19_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv20_model_data_cc",
    src = "conv20.tflite",
    out = "conv20_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv20_model_data_hdr",
    src = "conv20.tflite",
    out = "conv20_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv21_model_data_cc",
    src = "conv21.tflite",
    out = "conv21_model_data.cc",
)

generate_cc_arrays(
    name = "generated_conv21_model_data_hdr",
    src = "conv21.tflite",
    out = "conv21_model_data.h",
)

generate_cc_arrays(
    name = "generated_conv0_input0_int16_test_data_cc",
    src = "conv0_input0_int16.csv",
    out = "conv0_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv0_input0_int16_test_data_hdr",
    src = "conv0_input0_int16.csv",
    out = "conv0_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv0_golden_int16_test_data_cc",
    src = "conv0_golden_int16.csv",
    out = "conv0_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv0_golden_int16_test_data_hdr",
    src = "conv0_golden_int16.csv",
    out = "conv0_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv1_input0_int16_test_data_cc",
    src = "conv1_input0_int16.csv",
    out = "conv1_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv1_input0_int16_test_data_hdr",
    src = "conv1_input0_int16.csv",
    out = "conv1_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv1_golden_int16_test_data_cc",
    src = "conv1_golden_int16.csv",
    out = "conv1_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv1_golden_int16_test_data_hdr",
    src = "conv1_golden_int16.csv",
    out = "conv1_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv2_input0_int16_test_data_cc",
    src = "conv2_input0_int16.csv",
    out = "conv2_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv2_input0_int16_test_data_hdr",
    src = "conv2_input0_int16.csv",
    out = "conv2_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv2_golden_int16_test_data_cc",
    src = "conv2_golden_int16.csv",
    out = "conv2_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv2_golden_int16_test_data_hdr",
    src = "conv2_golden_int16.csv",
    out = "conv2_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv3_input0_int16_test_data_cc",
    src = "conv3_input0_int16.csv",
    out = "conv3_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv3_input0_int16_test_data_hdr",
    src = "conv3_input0_int16.csv",
    out = "conv3_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv3_golden_int16_test_data_cc",
    src = "conv3_golden_int16.csv",
    out = "conv3_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv3_golden_int16_test_data_hdr",
    src = "conv3_golden_int16.csv",
    out = "conv3_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv4_input0_int16_test_data_cc",
    src = "conv4_input0_int16.csv",
    out = "conv4_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv4_input0_int16_test_data_hdr",
    src = "conv4_input0_int16.csv",
    out = "conv4_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv4_golden_int16_test_data_cc",
    src = "conv4_golden_int16.csv",
    out = "conv4_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv4_golden_int16_test_data_hdr",
    src = "conv4_golden_int16.csv",
    out = "conv4_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv5_input0_int16_test_data_cc",
    src = "conv5_input0_int16.csv",
    out = "conv5_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv5_input0_int16_test_data_hdr",
    src = "conv5_input0_int16.csv",
    out = "conv5_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv5_golden_int16_test_data_cc",
    src = "conv5_golden_int16.csv",
    out = "conv5_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv5_golden_int16_test_data_hdr",
    src = "conv5_golden_int16.csv",
    out = "conv5_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv6_input0_int16_test_data_cc",
    src = "conv6_input0_int16.csv",
    out = "conv6_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv6_input0_int16_test_data_hdr",
    src = "conv6_input0_int16.csv",
    out = "conv6_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv6_golden_int16_test_data_cc",
    src = "conv6_golden_int16.csv",
    out = "conv6_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv6_golden_int16_test_data_hdr",
    src = "conv6_golden_int16.csv",
    out = "conv6_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv7_input0_int16_test_data_cc",
    src = "conv7_input0_int16.csv",
    out = "conv7_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv7_input0_int16_test_data_hdr",
    src = "conv7_input0_int16.csv",
    out = "conv7_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv7_golden_int16_test_data_cc",
    src = "conv7_golden_int16.csv",
    out = "conv7_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv7_golden_int16_test_data_hdr",
    src = "conv7_golden_int16.csv",
    out = "conv7_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv8_input0_int16_test_data_cc",
    src = "conv8_input0_int16.csv",
    out = "conv8_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv8_input0_int16_test_data_hdr",
    src = "conv8_input0_int16.csv",
    out = "conv8_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv8_golden_int16_test_data_cc",
    src = "conv8_golden_int16.csv",
    out = "conv8_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv8_golden_int16_test_data_hdr",
    src = "conv8_golden_int16.csv",
    out = "conv8_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv9_input0_int16_test_data_cc",
    src = "conv9_input0_int16.csv",
    out = "conv9_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv9_input0_int16_test_data_hdr",
    src = "conv9_input0_int16.csv",
    out = "conv9_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv9_golden_int16_test_data_cc",
    src = "conv9_golden_int16.csv",
    out = "conv9_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv9_golden_int16_test_data_hdr",
    src = "conv9_golden_int16.csv",
    out = "conv9_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv10_input0_int16_test_data_cc",
    src = "conv10_input0_int16.csv",
    out = "conv10_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv10_input0_int16_test_data_hdr",
    src = "conv10_input0_int16.csv",
    out = "conv10_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv10_golden_int16_test_data_cc",
    src = "conv10_golden_int16.csv",
    out = "conv10_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv10_golden_int16_test_data_hdr",
    src = "conv10_golden_int16.csv",
    out = "conv10_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv11_input0_int16_test_data_cc",
    src = "conv11_input0_int16.csv",
    out = "conv11_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv11_input0_int16_test_data_hdr",
    src = "conv11_input0_int16.csv",
    out = "conv11_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv11_golden_int16_test_data_cc",
    src = "conv11_golden_int16.csv",
    out = "conv11_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv11_golden_int16_test_data_hdr",
    src = "conv11_golden_int16.csv",
    out = "conv11_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv12_input0_int16_test_data_cc",
    src = "conv12_input0_int16.csv",
    out = "conv12_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv12_input0_int16_test_data_hdr",
    src = "conv12_input0_int16.csv",
    out = "conv12_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv12_golden_int16_test_data_cc",
    src = "conv12_golden_int16.csv",
    out = "conv12_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv12_golden_int16_test_data_hdr",
    src = "conv12_golden_int16.csv",
    out = "conv12_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv13_input0_int16_test_data_cc",
    src = "conv13_input0_int16.csv",
    out = "conv13_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv13_input0_int16_test_data_hdr",
    src = "conv13_input0_int16.csv",
    out = "conv13_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv13_golden_int16_test_data_cc",
    src = "conv13_golden_int16.csv",
    out = "conv13_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv13_golden_int16_test_data_hdr",
    src = "conv13_golden_int16.csv",
    out = "conv13_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv14_input0_int16_test_data_cc",
    src = "conv14_input0_int16.csv",
    out = "conv14_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv14_input0_int16_test_data_hdr",
    src = "conv14_input0_int16.csv",
    out = "conv14_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv14_golden_int16_test_data_cc",
    src = "conv14_golden_int16.csv",
    out = "conv14_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv14_golden_int16_test_data_hdr",
    src = "conv14_golden_int16.csv",
    out = "conv14_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv15_input0_int16_test_data_cc",
    src = "conv15_input0_int16.csv",
    out = "conv15_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv15_input0_int16_test_data_hdr",
    src = "conv15_input0_int16.csv",
    out = "conv15_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv15_golden_int16_test_data_cc",
    src = "conv15_golden_int16.csv",
    out = "conv15_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv15_golden_int16_test_data_hdr",
    src = "conv15_golden_int16.csv",
    out = "conv15_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv16_input0_int16_test_data_cc",
    src = "conv16_input0_int16.csv",
    out = "conv16_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv16_input0_int16_test_data_hdr",
    src = "conv16_input0_int16.csv",
    out = "conv16_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv16_golden_int16_test_data_cc",
    src = "conv16_golden_int16.csv",
    out = "conv16_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv16_golden_int16_test_data_hdr",
    src = "conv16_golden_int16.csv",
    out = "conv16_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv17_input0_int16_test_data_cc",
    src = "conv17_input0_int16.csv",
    out = "conv17_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv17_input0_int16_test_data_hdr",
    src = "conv17_input0_int16.csv",
    out = "conv17_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv17_golden_int16_test_data_cc",
    src = "conv17_golden_int16.csv",
    out = "conv17_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv17_golden_int16_test_data_hdr",
    src = "conv17_golden_int16.csv",
    out = "conv17_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv18_input0_int16_test_data_cc",
    src = "conv18_input0_int16.csv",
    out = "conv18_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv18_input0_int16_test_data_hdr",
    src = "conv18_input0_int16.csv",
    out = "conv18_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv18_golden_int16_test_data_cc",
    src = "conv18_golden_int16.csv",
    out = "conv18_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv18_golden_int16_test_data_hdr",
    src = "conv18_golden_int16.csv",
    out = "conv18_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv19_input0_int16_test_data_cc",
    src = "conv19_input0_int16.csv",
    out = "conv19_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv19_input0_int16_test_data_hdr",
    src = "conv19_input0_int16.csv",
    out = "conv19_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv19_golden_int16_test_data_cc",
    src = "conv19_golden_int16.csv",
    out = "conv19_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv19_golden_int16_test_data_hdr",
    src = "conv19_golden_int16.csv",
    out = "conv19_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv20_input0_int16_test_data_cc",
    src = "conv20_input0_int16.csv",
    out = "conv20_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv20_input0_int16_test_data_hdr",
    src = "conv20_input0_int16.csv",
    out = "conv20_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv20_golden_int16_test_data_cc",
    src = "conv20_golden_int16.csv",
    out = "conv20_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv20_golden_int16_test_data_hdr",
    src = "conv20_golden_int16.csv",
    out = "conv20_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv21_input0_int16_test_data_cc",
    src = "conv21_input0_int16.csv",
    out = "conv21_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv21_input0_int16_test_data_hdr",
    src = "conv21_input0_int16.csv",
    out = "conv21_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_conv21_golden_int16_test_data_cc",
    src = "conv21_golden_int16.csv",
    out = "conv21_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_conv21_golden_int16_test_data_hdr",
    src = "conv21_golden_int16.csv",
    out = "conv21_golden_int16_test_data.h",
)

tflm_cc_library(
    name = "models_and_testdata",
    srcs = [
        "generated_conv0_golden_int16_test_data_cc",
        "generated_conv0_input0_int16_test_data_cc",
        "generated_conv0_model_data_cc",
        "generated_conv10_golden_int16_test_data_cc",
        "generated_conv10_input0_int16_test_data_cc",
        "generated_conv10_model_data_cc",
        "generated_conv11_golden_int16_test_data_cc",
        "generated_conv11_input0_int16_test_data_cc",
        "generated_conv11_model_data_cc",
        "generated_conv12_golden_int16_test_data_cc",
        "generated_conv12_input0_int16_test_data_cc",
        "generated_conv12_model_data_cc",
        "generated_conv13_golden_int16_test_data_cc",
        "generated_conv13_input0_int16_test_data_cc",
        "generated_conv13_model_data_cc",
        "generated_conv14_golden_int16_test_data_cc",
        "generated_conv14_input0_int16_test_data_cc",
        "generated_conv14_model_data_cc",
        "generated_conv15_golden_int16_test_data_cc",
        "generated_conv15_input0_int16_test_data_cc",
        "generated_conv15_model_data_cc",
        "generated_conv16_golden_int16_test_data_cc",
        "generated_conv16_input0_int16_test_data_cc",
        "generated_conv16_model_data_cc",
        "generated_conv17_golden_int16_test_data_cc",
        "generated_conv17_input0_int16_test_data_cc",
        "generated_conv17_model_data_cc",
        "generated_conv18_golden_int16_test_data_cc",
        "generated_conv18_input0_int16_test_data_cc",
        "generated_conv18_model_data_cc",
        "generated_conv19_golden_int16_test_data_cc",
        "generated_conv19_input0_int16_test_data_cc",
        "generated_conv19_model_data_cc",
        "generated_conv1_golden_int16_test_data_cc",
        "generated_conv1_input0_int16_test_data_cc",
        "generated_conv1_model_data_cc",
        "generated_conv20_golden_int16_test_data_cc",
        "generated_conv20_input0_int16_test_data_cc",
        "generated_conv20_model_data_cc",
        "generated_conv21_golden_int16_test_data_cc",
        "generated_conv21_input0_int16_test_data_cc",
        "generated_conv21_model_data_cc",
        "generated_conv2_golden_int16_test_data_cc",
        "generated_conv2_input0_int16_test_data_cc",
        "generated_conv2_model_data_cc",
        "generated_conv3_golden_int16_test_data_cc",
        "generated_conv3_input0_int16_test_data_cc",
        "generated_conv3_model_data_cc",
        "generated_conv4_golden_int16_test_data_cc",
        "generated_conv4_input0_int16_test_data_cc",
        "generated_conv4_model_data_cc",
        "generated_conv5_golden_int16_test_data_cc",
        "generated_conv5_input0_int16_test_data_cc",
        "generated_conv5_model_data_cc",
        "generated_conv6_golden_int16_test_data_cc",
        "generated_conv6_input0_int16_test_data_cc",
        "generated_conv6_model_data_cc",
        "generated_conv7_golden_int16_test_data_cc",
        "generated_conv7_input0_int16_test_data_cc",
        "generated_conv7_model_data_cc",
        "generated_conv8_golden_int16_test_data_cc",
        "generated_conv8_input0_int16_test_data_cc",
        "generated_conv8_model_data_cc",
        "generated_conv9_golden_int16_test_data_cc",
        "generated_conv9_input0_int16_test_data_cc",
        "generated_conv9_model_data_cc",
    ],
    hdrs = [
        "generated_conv0_golden_int16_test_data_hdr",
        "generated_conv0_input0_int16_test_data_hdr",
        "generated_conv0_model_data_hdr",
        "generated_conv10_golden_int16_test_data_hdr",
        "generated_conv10_input0_int16_test_data_hdr",
        "generated_conv10_model_data_hdr",
        "generated_conv11_golden_int16_test_data_hdr",
        "generated_conv11_input0_int16_test_data_hdr",
        "generated_conv11_model_data_hdr",
        "generated_conv12_golden_int16_test_data_hdr",
        "generated_conv12_input0_int16_test_data_hdr",
        "generated_conv12_model_data_hdr",
        "generated_conv13_golden_int16_test_data_hdr",
        "generated_conv13_input0_int16_test_data_hdr",
        "generated_conv13_model_data_hdr",
        "generated_conv14_golden_int16_test_data_hdr",
        "generated_conv14_input0_int16_test_data_hdr",
        "generated_conv14_model_data_hdr",
        "generated_conv15_golden_int16_test_data_hdr",
        "generated_conv15_input0_int16_test_data_hdr",
        "generated_conv15_model_data_hdr",
        "generated_conv16_golden_int16_test_data_hdr",
        "generated_conv16_input0_int16_test_data_hdr",
        "generated_conv16_model_data_hdr",
        "generated_conv17_golden_int16_test_data_hdr",
        "generated_conv17_input0_int16_test_data_hdr",
        "generated_conv17_model_data_hdr",
        "generated_conv18_golden_int16_test_data_hdr",
        "generated_conv18_input0_int16_test_data_hdr",
        "generated_conv18_model_data_hdr",
        "generated_conv19_golden_int16_test_data_hdr",
        "generated_conv19_input0_int16_test_data_hdr",
        "generated_conv19_model_data_hdr",
        "generated_conv1_golden_int16_test_data_hdr",
        "generated_conv1_input0_int16_test_data_hdr",
        "generated_conv1_model_data_hdr",
        "generated_conv20_golden_int16_test_data_hdr",
        "generated_conv20_input0_int16_test_data_hdr",
        "generated_conv20_model_data_hdr",
        "generated_conv21_golden_int16_test_data_hdr",
        "generated_conv21_input0_int16_test_data_hdr",
        "generated_conv21_model_data_hdr",
        "generated_conv2_golden_int16_test_data_hdr",
        "generated_conv2_input0_int16_test_data_hdr",
        "generated_conv2_model_data_hdr",
        "generated_conv3_golden_int16_test_data_hdr",
        "generated_conv3_input0_int16_test_data_hdr",
        "generated_conv3_model_data_hdr",
        "generated_conv4_golden_int16_test_data_hdr",
        "generated_conv4_input0_int16_test_data_hdr",
        "generated_conv4_model_data_hdr",
        "generated_conv5_golden_int16_test_data_hdr",
        "generated_conv5_input0_int16_test_data_hdr",
        "generated_conv5_model_data_hdr",
        "generated_conv6_golden_int16_test_data_hdr",
        "generated_conv6_input0_int16_test_data_hdr",
        "generated_conv6_model_data_hdr",
        "generated_conv7_golden_int16_test_data_hdr",
        "generated_conv7_input0_int16_test_data_hdr",
        "generated_conv7_model_data_hdr",
        "generated_conv8_golden_int16_test_data_hdr",
        "generated_conv8_input0_int16_test_data_hdr",
        "generated_conv8_model_data_hdr",
        "generated_conv9_golden_int16_test_data_hdr",
        "generated_conv9_input0_int16_test_data_hdr",
        "generated_conv9_model_data_hdr",
    ],
)

tflm_cc_test(
    name = "integration_test",
    srcs = [
        "integration_tests.cc",
    ],
    deps = [
        ":models_and_testdata",
        "//python/tflite_micro:python_ops_resolver",
        "//tensorflow/lite/micro:micro_framework",
        "//tensorflow/lite/micro:micro_log",
        "//tensorflow/lite/micro:micro_resource_variable",
        "//tensorflow/lite/micro:op_resolvers",
        "//tensorflow/lite/micro:recording_allocators",
        "//tensorflow/lite/micro/testing:micro_test",
    ],
)
