# Description:
#   generated integration test for one specific kernel in a model.
load(
    "//tensorflow/lite/micro:build_def.bzl",
    "generate_cc_arrays",
    "tflm_cc_library",
    "tflm_cc_test",
)

package(
    default_visibility = ["//visibility:public"],
    # Disabling layering_check because of http://b/177257332
    features = ["-layering_check"],
    licenses = ["notice"],
)

generate_cc_arrays(
    name = "generated_strided_slice0_model_data_cc",
    src = "strided_slice0.tflite",
    out = "strided_slice0_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice0_model_data_hdr",
    src = "strided_slice0.tflite",
    out = "strided_slice0_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice1_model_data_cc",
    src = "strided_slice1.tflite",
    out = "strided_slice1_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice1_model_data_hdr",
    src = "strided_slice1.tflite",
    out = "strided_slice1_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice2_model_data_cc",
    src = "strided_slice2.tflite",
    out = "strided_slice2_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice2_model_data_hdr",
    src = "strided_slice2.tflite",
    out = "strided_slice2_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice3_model_data_cc",
    src = "strided_slice3.tflite",
    out = "strided_slice3_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice3_model_data_hdr",
    src = "strided_slice3.tflite",
    out = "strided_slice3_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice4_model_data_cc",
    src = "strided_slice4.tflite",
    out = "strided_slice4_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice4_model_data_hdr",
    src = "strided_slice4.tflite",
    out = "strided_slice4_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice5_model_data_cc",
    src = "strided_slice5.tflite",
    out = "strided_slice5_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice5_model_data_hdr",
    src = "strided_slice5.tflite",
    out = "strided_slice5_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice6_model_data_cc",
    src = "strided_slice6.tflite",
    out = "strided_slice6_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice6_model_data_hdr",
    src = "strided_slice6.tflite",
    out = "strided_slice6_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice7_model_data_cc",
    src = "strided_slice7.tflite",
    out = "strided_slice7_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice7_model_data_hdr",
    src = "strided_slice7.tflite",
    out = "strided_slice7_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice8_model_data_cc",
    src = "strided_slice8.tflite",
    out = "strided_slice8_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice8_model_data_hdr",
    src = "strided_slice8.tflite",
    out = "strided_slice8_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice9_model_data_cc",
    src = "strided_slice9.tflite",
    out = "strided_slice9_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice9_model_data_hdr",
    src = "strided_slice9.tflite",
    out = "strided_slice9_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice10_model_data_cc",
    src = "strided_slice10.tflite",
    out = "strided_slice10_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice10_model_data_hdr",
    src = "strided_slice10.tflite",
    out = "strided_slice10_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice11_model_data_cc",
    src = "strided_slice11.tflite",
    out = "strided_slice11_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice11_model_data_hdr",
    src = "strided_slice11.tflite",
    out = "strided_slice11_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice12_model_data_cc",
    src = "strided_slice12.tflite",
    out = "strided_slice12_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice12_model_data_hdr",
    src = "strided_slice12.tflite",
    out = "strided_slice12_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice13_model_data_cc",
    src = "strided_slice13.tflite",
    out = "strided_slice13_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice13_model_data_hdr",
    src = "strided_slice13.tflite",
    out = "strided_slice13_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice14_model_data_cc",
    src = "strided_slice14.tflite",
    out = "strided_slice14_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice14_model_data_hdr",
    src = "strided_slice14.tflite",
    out = "strided_slice14_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice15_model_data_cc",
    src = "strided_slice15.tflite",
    out = "strided_slice15_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice15_model_data_hdr",
    src = "strided_slice15.tflite",
    out = "strided_slice15_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice16_model_data_cc",
    src = "strided_slice16.tflite",
    out = "strided_slice16_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice16_model_data_hdr",
    src = "strided_slice16.tflite",
    out = "strided_slice16_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice17_model_data_cc",
    src = "strided_slice17.tflite",
    out = "strided_slice17_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice17_model_data_hdr",
    src = "strided_slice17.tflite",
    out = "strided_slice17_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice18_model_data_cc",
    src = "strided_slice18.tflite",
    out = "strided_slice18_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice18_model_data_hdr",
    src = "strided_slice18.tflite",
    out = "strided_slice18_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice19_model_data_cc",
    src = "strided_slice19.tflite",
    out = "strided_slice19_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice19_model_data_hdr",
    src = "strided_slice19.tflite",
    out = "strided_slice19_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice20_model_data_cc",
    src = "strided_slice20.tflite",
    out = "strided_slice20_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice20_model_data_hdr",
    src = "strided_slice20.tflite",
    out = "strided_slice20_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice21_model_data_cc",
    src = "strided_slice21.tflite",
    out = "strided_slice21_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice21_model_data_hdr",
    src = "strided_slice21.tflite",
    out = "strided_slice21_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice22_model_data_cc",
    src = "strided_slice22.tflite",
    out = "strided_slice22_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice22_model_data_hdr",
    src = "strided_slice22.tflite",
    out = "strided_slice22_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice23_model_data_cc",
    src = "strided_slice23.tflite",
    out = "strided_slice23_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice23_model_data_hdr",
    src = "strided_slice23.tflite",
    out = "strided_slice23_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice24_model_data_cc",
    src = "strided_slice24.tflite",
    out = "strided_slice24_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice24_model_data_hdr",
    src = "strided_slice24.tflite",
    out = "strided_slice24_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice25_model_data_cc",
    src = "strided_slice25.tflite",
    out = "strided_slice25_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice25_model_data_hdr",
    src = "strided_slice25.tflite",
    out = "strided_slice25_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice26_model_data_cc",
    src = "strided_slice26.tflite",
    out = "strided_slice26_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice26_model_data_hdr",
    src = "strided_slice26.tflite",
    out = "strided_slice26_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice27_model_data_cc",
    src = "strided_slice27.tflite",
    out = "strided_slice27_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice27_model_data_hdr",
    src = "strided_slice27.tflite",
    out = "strided_slice27_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice28_model_data_cc",
    src = "strided_slice28.tflite",
    out = "strided_slice28_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice28_model_data_hdr",
    src = "strided_slice28.tflite",
    out = "strided_slice28_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice29_model_data_cc",
    src = "strided_slice29.tflite",
    out = "strided_slice29_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice29_model_data_hdr",
    src = "strided_slice29.tflite",
    out = "strided_slice29_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice30_model_data_cc",
    src = "strided_slice30.tflite",
    out = "strided_slice30_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice30_model_data_hdr",
    src = "strided_slice30.tflite",
    out = "strided_slice30_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice31_model_data_cc",
    src = "strided_slice31.tflite",
    out = "strided_slice31_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice31_model_data_hdr",
    src = "strided_slice31.tflite",
    out = "strided_slice31_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice32_model_data_cc",
    src = "strided_slice32.tflite",
    out = "strided_slice32_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice32_model_data_hdr",
    src = "strided_slice32.tflite",
    out = "strided_slice32_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice33_model_data_cc",
    src = "strided_slice33.tflite",
    out = "strided_slice33_model_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice33_model_data_hdr",
    src = "strided_slice33.tflite",
    out = "strided_slice33_model_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice0_input0_int16_test_data_cc",
    src = "strided_slice0_input0_int16.csv",
    out = "strided_slice0_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice0_input0_int16_test_data_hdr",
    src = "strided_slice0_input0_int16.csv",
    out = "strided_slice0_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice0_golden_int16_test_data_cc",
    src = "strided_slice0_golden_int16.csv",
    out = "strided_slice0_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice0_golden_int16_test_data_hdr",
    src = "strided_slice0_golden_int16.csv",
    out = "strided_slice0_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice1_input0_int16_test_data_cc",
    src = "strided_slice1_input0_int16.csv",
    out = "strided_slice1_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice1_input0_int16_test_data_hdr",
    src = "strided_slice1_input0_int16.csv",
    out = "strided_slice1_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice1_golden_int16_test_data_cc",
    src = "strided_slice1_golden_int16.csv",
    out = "strided_slice1_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice1_golden_int16_test_data_hdr",
    src = "strided_slice1_golden_int16.csv",
    out = "strided_slice1_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice2_input0_int16_test_data_cc",
    src = "strided_slice2_input0_int16.csv",
    out = "strided_slice2_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice2_input0_int16_test_data_hdr",
    src = "strided_slice2_input0_int16.csv",
    out = "strided_slice2_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice2_golden_int16_test_data_cc",
    src = "strided_slice2_golden_int16.csv",
    out = "strided_slice2_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice2_golden_int16_test_data_hdr",
    src = "strided_slice2_golden_int16.csv",
    out = "strided_slice2_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice3_input0_int16_test_data_cc",
    src = "strided_slice3_input0_int16.csv",
    out = "strided_slice3_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice3_input0_int16_test_data_hdr",
    src = "strided_slice3_input0_int16.csv",
    out = "strided_slice3_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice3_golden_int16_test_data_cc",
    src = "strided_slice3_golden_int16.csv",
    out = "strided_slice3_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice3_golden_int16_test_data_hdr",
    src = "strided_slice3_golden_int16.csv",
    out = "strided_slice3_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice4_input0_int16_test_data_cc",
    src = "strided_slice4_input0_int16.csv",
    out = "strided_slice4_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice4_input0_int16_test_data_hdr",
    src = "strided_slice4_input0_int16.csv",
    out = "strided_slice4_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice4_golden_int16_test_data_cc",
    src = "strided_slice4_golden_int16.csv",
    out = "strided_slice4_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice4_golden_int16_test_data_hdr",
    src = "strided_slice4_golden_int16.csv",
    out = "strided_slice4_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice5_input0_int16_test_data_cc",
    src = "strided_slice5_input0_int16.csv",
    out = "strided_slice5_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice5_input0_int16_test_data_hdr",
    src = "strided_slice5_input0_int16.csv",
    out = "strided_slice5_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice5_golden_int16_test_data_cc",
    src = "strided_slice5_golden_int16.csv",
    out = "strided_slice5_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice5_golden_int16_test_data_hdr",
    src = "strided_slice5_golden_int16.csv",
    out = "strided_slice5_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice6_input0_int16_test_data_cc",
    src = "strided_slice6_input0_int16.csv",
    out = "strided_slice6_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice6_input0_int16_test_data_hdr",
    src = "strided_slice6_input0_int16.csv",
    out = "strided_slice6_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice6_golden_int16_test_data_cc",
    src = "strided_slice6_golden_int16.csv",
    out = "strided_slice6_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice6_golden_int16_test_data_hdr",
    src = "strided_slice6_golden_int16.csv",
    out = "strided_slice6_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice7_input0_int16_test_data_cc",
    src = "strided_slice7_input0_int16.csv",
    out = "strided_slice7_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice7_input0_int16_test_data_hdr",
    src = "strided_slice7_input0_int16.csv",
    out = "strided_slice7_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice7_golden_int16_test_data_cc",
    src = "strided_slice7_golden_int16.csv",
    out = "strided_slice7_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice7_golden_int16_test_data_hdr",
    src = "strided_slice7_golden_int16.csv",
    out = "strided_slice7_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice8_input0_int16_test_data_cc",
    src = "strided_slice8_input0_int16.csv",
    out = "strided_slice8_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice8_input0_int16_test_data_hdr",
    src = "strided_slice8_input0_int16.csv",
    out = "strided_slice8_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice8_golden_int16_test_data_cc",
    src = "strided_slice8_golden_int16.csv",
    out = "strided_slice8_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice8_golden_int16_test_data_hdr",
    src = "strided_slice8_golden_int16.csv",
    out = "strided_slice8_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice9_input0_int16_test_data_cc",
    src = "strided_slice9_input0_int16.csv",
    out = "strided_slice9_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice9_input0_int16_test_data_hdr",
    src = "strided_slice9_input0_int16.csv",
    out = "strided_slice9_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice9_golden_int16_test_data_cc",
    src = "strided_slice9_golden_int16.csv",
    out = "strided_slice9_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice9_golden_int16_test_data_hdr",
    src = "strided_slice9_golden_int16.csv",
    out = "strided_slice9_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice10_input0_int16_test_data_cc",
    src = "strided_slice10_input0_int16.csv",
    out = "strided_slice10_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice10_input0_int16_test_data_hdr",
    src = "strided_slice10_input0_int16.csv",
    out = "strided_slice10_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice10_golden_int16_test_data_cc",
    src = "strided_slice10_golden_int16.csv",
    out = "strided_slice10_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice10_golden_int16_test_data_hdr",
    src = "strided_slice10_golden_int16.csv",
    out = "strided_slice10_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice11_input0_int16_test_data_cc",
    src = "strided_slice11_input0_int16.csv",
    out = "strided_slice11_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice11_input0_int16_test_data_hdr",
    src = "strided_slice11_input0_int16.csv",
    out = "strided_slice11_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice11_golden_int16_test_data_cc",
    src = "strided_slice11_golden_int16.csv",
    out = "strided_slice11_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice11_golden_int16_test_data_hdr",
    src = "strided_slice11_golden_int16.csv",
    out = "strided_slice11_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice12_input0_int16_test_data_cc",
    src = "strided_slice12_input0_int16.csv",
    out = "strided_slice12_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice12_input0_int16_test_data_hdr",
    src = "strided_slice12_input0_int16.csv",
    out = "strided_slice12_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice12_golden_int16_test_data_cc",
    src = "strided_slice12_golden_int16.csv",
    out = "strided_slice12_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice12_golden_int16_test_data_hdr",
    src = "strided_slice12_golden_int16.csv",
    out = "strided_slice12_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice13_input0_int16_test_data_cc",
    src = "strided_slice13_input0_int16.csv",
    out = "strided_slice13_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice13_input0_int16_test_data_hdr",
    src = "strided_slice13_input0_int16.csv",
    out = "strided_slice13_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice13_golden_int16_test_data_cc",
    src = "strided_slice13_golden_int16.csv",
    out = "strided_slice13_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice13_golden_int16_test_data_hdr",
    src = "strided_slice13_golden_int16.csv",
    out = "strided_slice13_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice14_input0_int16_test_data_cc",
    src = "strided_slice14_input0_int16.csv",
    out = "strided_slice14_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice14_input0_int16_test_data_hdr",
    src = "strided_slice14_input0_int16.csv",
    out = "strided_slice14_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice14_golden_int16_test_data_cc",
    src = "strided_slice14_golden_int16.csv",
    out = "strided_slice14_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice14_golden_int16_test_data_hdr",
    src = "strided_slice14_golden_int16.csv",
    out = "strided_slice14_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice15_input0_int16_test_data_cc",
    src = "strided_slice15_input0_int16.csv",
    out = "strided_slice15_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice15_input0_int16_test_data_hdr",
    src = "strided_slice15_input0_int16.csv",
    out = "strided_slice15_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice15_golden_int16_test_data_cc",
    src = "strided_slice15_golden_int16.csv",
    out = "strided_slice15_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice15_golden_int16_test_data_hdr",
    src = "strided_slice15_golden_int16.csv",
    out = "strided_slice15_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice16_input0_int16_test_data_cc",
    src = "strided_slice16_input0_int16.csv",
    out = "strided_slice16_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice16_input0_int16_test_data_hdr",
    src = "strided_slice16_input0_int16.csv",
    out = "strided_slice16_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice16_golden_int16_test_data_cc",
    src = "strided_slice16_golden_int16.csv",
    out = "strided_slice16_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice16_golden_int16_test_data_hdr",
    src = "strided_slice16_golden_int16.csv",
    out = "strided_slice16_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice17_input0_int16_test_data_cc",
    src = "strided_slice17_input0_int16.csv",
    out = "strided_slice17_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice17_input0_int16_test_data_hdr",
    src = "strided_slice17_input0_int16.csv",
    out = "strided_slice17_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice17_golden_int16_test_data_cc",
    src = "strided_slice17_golden_int16.csv",
    out = "strided_slice17_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice17_golden_int16_test_data_hdr",
    src = "strided_slice17_golden_int16.csv",
    out = "strided_slice17_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice18_input0_int16_test_data_cc",
    src = "strided_slice18_input0_int16.csv",
    out = "strided_slice18_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice18_input0_int16_test_data_hdr",
    src = "strided_slice18_input0_int16.csv",
    out = "strided_slice18_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice18_golden_int16_test_data_cc",
    src = "strided_slice18_golden_int16.csv",
    out = "strided_slice18_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice18_golden_int16_test_data_hdr",
    src = "strided_slice18_golden_int16.csv",
    out = "strided_slice18_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice19_input0_int16_test_data_cc",
    src = "strided_slice19_input0_int16.csv",
    out = "strided_slice19_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice19_input0_int16_test_data_hdr",
    src = "strided_slice19_input0_int16.csv",
    out = "strided_slice19_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice19_golden_int16_test_data_cc",
    src = "strided_slice19_golden_int16.csv",
    out = "strided_slice19_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice19_golden_int16_test_data_hdr",
    src = "strided_slice19_golden_int16.csv",
    out = "strided_slice19_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice20_input0_int16_test_data_cc",
    src = "strided_slice20_input0_int16.csv",
    out = "strided_slice20_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice20_input0_int16_test_data_hdr",
    src = "strided_slice20_input0_int16.csv",
    out = "strided_slice20_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice20_golden_int16_test_data_cc",
    src = "strided_slice20_golden_int16.csv",
    out = "strided_slice20_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice20_golden_int16_test_data_hdr",
    src = "strided_slice20_golden_int16.csv",
    out = "strided_slice20_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice21_input0_int16_test_data_cc",
    src = "strided_slice21_input0_int16.csv",
    out = "strided_slice21_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice21_input0_int16_test_data_hdr",
    src = "strided_slice21_input0_int16.csv",
    out = "strided_slice21_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice21_golden_int16_test_data_cc",
    src = "strided_slice21_golden_int16.csv",
    out = "strided_slice21_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice21_golden_int16_test_data_hdr",
    src = "strided_slice21_golden_int16.csv",
    out = "strided_slice21_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice22_input0_int16_test_data_cc",
    src = "strided_slice22_input0_int16.csv",
    out = "strided_slice22_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice22_input0_int16_test_data_hdr",
    src = "strided_slice22_input0_int16.csv",
    out = "strided_slice22_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice22_golden_int16_test_data_cc",
    src = "strided_slice22_golden_int16.csv",
    out = "strided_slice22_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice22_golden_int16_test_data_hdr",
    src = "strided_slice22_golden_int16.csv",
    out = "strided_slice22_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice23_input0_int16_test_data_cc",
    src = "strided_slice23_input0_int16.csv",
    out = "strided_slice23_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice23_input0_int16_test_data_hdr",
    src = "strided_slice23_input0_int16.csv",
    out = "strided_slice23_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice23_golden_int16_test_data_cc",
    src = "strided_slice23_golden_int16.csv",
    out = "strided_slice23_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice23_golden_int16_test_data_hdr",
    src = "strided_slice23_golden_int16.csv",
    out = "strided_slice23_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice24_input0_int16_test_data_cc",
    src = "strided_slice24_input0_int16.csv",
    out = "strided_slice24_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice24_input0_int16_test_data_hdr",
    src = "strided_slice24_input0_int16.csv",
    out = "strided_slice24_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice24_golden_int16_test_data_cc",
    src = "strided_slice24_golden_int16.csv",
    out = "strided_slice24_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice24_golden_int16_test_data_hdr",
    src = "strided_slice24_golden_int16.csv",
    out = "strided_slice24_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice25_input0_int16_test_data_cc",
    src = "strided_slice25_input0_int16.csv",
    out = "strided_slice25_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice25_input0_int16_test_data_hdr",
    src = "strided_slice25_input0_int16.csv",
    out = "strided_slice25_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice25_golden_int16_test_data_cc",
    src = "strided_slice25_golden_int16.csv",
    out = "strided_slice25_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice25_golden_int16_test_data_hdr",
    src = "strided_slice25_golden_int16.csv",
    out = "strided_slice25_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice26_input0_int16_test_data_cc",
    src = "strided_slice26_input0_int16.csv",
    out = "strided_slice26_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice26_input0_int16_test_data_hdr",
    src = "strided_slice26_input0_int16.csv",
    out = "strided_slice26_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice26_golden_int16_test_data_cc",
    src = "strided_slice26_golden_int16.csv",
    out = "strided_slice26_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice26_golden_int16_test_data_hdr",
    src = "strided_slice26_golden_int16.csv",
    out = "strided_slice26_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice27_input0_int16_test_data_cc",
    src = "strided_slice27_input0_int16.csv",
    out = "strided_slice27_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice27_input0_int16_test_data_hdr",
    src = "strided_slice27_input0_int16.csv",
    out = "strided_slice27_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice27_golden_int16_test_data_cc",
    src = "strided_slice27_golden_int16.csv",
    out = "strided_slice27_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice27_golden_int16_test_data_hdr",
    src = "strided_slice27_golden_int16.csv",
    out = "strided_slice27_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice28_input0_int16_test_data_cc",
    src = "strided_slice28_input0_int16.csv",
    out = "strided_slice28_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice28_input0_int16_test_data_hdr",
    src = "strided_slice28_input0_int16.csv",
    out = "strided_slice28_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice28_golden_int16_test_data_cc",
    src = "strided_slice28_golden_int16.csv",
    out = "strided_slice28_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice28_golden_int16_test_data_hdr",
    src = "strided_slice28_golden_int16.csv",
    out = "strided_slice28_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice29_input0_int16_test_data_cc",
    src = "strided_slice29_input0_int16.csv",
    out = "strided_slice29_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice29_input0_int16_test_data_hdr",
    src = "strided_slice29_input0_int16.csv",
    out = "strided_slice29_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice29_golden_int16_test_data_cc",
    src = "strided_slice29_golden_int16.csv",
    out = "strided_slice29_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice29_golden_int16_test_data_hdr",
    src = "strided_slice29_golden_int16.csv",
    out = "strided_slice29_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice30_input0_int16_test_data_cc",
    src = "strided_slice30_input0_int16.csv",
    out = "strided_slice30_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice30_input0_int16_test_data_hdr",
    src = "strided_slice30_input0_int16.csv",
    out = "strided_slice30_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice30_golden_int16_test_data_cc",
    src = "strided_slice30_golden_int16.csv",
    out = "strided_slice30_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice30_golden_int16_test_data_hdr",
    src = "strided_slice30_golden_int16.csv",
    out = "strided_slice30_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice31_input0_int16_test_data_cc",
    src = "strided_slice31_input0_int16.csv",
    out = "strided_slice31_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice31_input0_int16_test_data_hdr",
    src = "strided_slice31_input0_int16.csv",
    out = "strided_slice31_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice31_golden_int16_test_data_cc",
    src = "strided_slice31_golden_int16.csv",
    out = "strided_slice31_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice31_golden_int16_test_data_hdr",
    src = "strided_slice31_golden_int16.csv",
    out = "strided_slice31_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice32_input0_int16_test_data_cc",
    src = "strided_slice32_input0_int16.csv",
    out = "strided_slice32_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice32_input0_int16_test_data_hdr",
    src = "strided_slice32_input0_int16.csv",
    out = "strided_slice32_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice32_golden_int16_test_data_cc",
    src = "strided_slice32_golden_int16.csv",
    out = "strided_slice32_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice32_golden_int16_test_data_hdr",
    src = "strided_slice32_golden_int16.csv",
    out = "strided_slice32_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice33_input0_int16_test_data_cc",
    src = "strided_slice33_input0_int16.csv",
    out = "strided_slice33_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice33_input0_int16_test_data_hdr",
    src = "strided_slice33_input0_int16.csv",
    out = "strided_slice33_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_strided_slice33_golden_int16_test_data_cc",
    src = "strided_slice33_golden_int16.csv",
    out = "strided_slice33_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_strided_slice33_golden_int16_test_data_hdr",
    src = "strided_slice33_golden_int16.csv",
    out = "strided_slice33_golden_int16_test_data.h",
)

tflm_cc_library(
    name = "models_and_testdata",
    srcs = [
        "generated_strided_slice0_golden_int16_test_data_cc",
        "generated_strided_slice0_input0_int16_test_data_cc",
        "generated_strided_slice0_model_data_cc",
        "generated_strided_slice10_golden_int16_test_data_cc",
        "generated_strided_slice10_input0_int16_test_data_cc",
        "generated_strided_slice10_model_data_cc",
        "generated_strided_slice11_golden_int16_test_data_cc",
        "generated_strided_slice11_input0_int16_test_data_cc",
        "generated_strided_slice11_model_data_cc",
        "generated_strided_slice12_golden_int16_test_data_cc",
        "generated_strided_slice12_input0_int16_test_data_cc",
        "generated_strided_slice12_model_data_cc",
        "generated_strided_slice13_golden_int16_test_data_cc",
        "generated_strided_slice13_input0_int16_test_data_cc",
        "generated_strided_slice13_model_data_cc",
        "generated_strided_slice14_golden_int16_test_data_cc",
        "generated_strided_slice14_input0_int16_test_data_cc",
        "generated_strided_slice14_model_data_cc",
        "generated_strided_slice15_golden_int16_test_data_cc",
        "generated_strided_slice15_input0_int16_test_data_cc",
        "generated_strided_slice15_model_data_cc",
        "generated_strided_slice16_golden_int16_test_data_cc",
        "generated_strided_slice16_input0_int16_test_data_cc",
        "generated_strided_slice16_model_data_cc",
        "generated_strided_slice17_golden_int16_test_data_cc",
        "generated_strided_slice17_input0_int16_test_data_cc",
        "generated_strided_slice17_model_data_cc",
        "generated_strided_slice18_golden_int16_test_data_cc",
        "generated_strided_slice18_input0_int16_test_data_cc",
        "generated_strided_slice18_model_data_cc",
        "generated_strided_slice19_golden_int16_test_data_cc",
        "generated_strided_slice19_input0_int16_test_data_cc",
        "generated_strided_slice19_model_data_cc",
        "generated_strided_slice1_golden_int16_test_data_cc",
        "generated_strided_slice1_input0_int16_test_data_cc",
        "generated_strided_slice1_model_data_cc",
        "generated_strided_slice20_golden_int16_test_data_cc",
        "generated_strided_slice20_input0_int16_test_data_cc",
        "generated_strided_slice20_model_data_cc",
        "generated_strided_slice21_golden_int16_test_data_cc",
        "generated_strided_slice21_input0_int16_test_data_cc",
        "generated_strided_slice21_model_data_cc",
        "generated_strided_slice22_golden_int16_test_data_cc",
        "generated_strided_slice22_input0_int16_test_data_cc",
        "generated_strided_slice22_model_data_cc",
        "generated_strided_slice23_golden_int16_test_data_cc",
        "generated_strided_slice23_input0_int16_test_data_cc",
        "generated_strided_slice23_model_data_cc",
        "generated_strided_slice24_golden_int16_test_data_cc",
        "generated_strided_slice24_input0_int16_test_data_cc",
        "generated_strided_slice24_model_data_cc",
        "generated_strided_slice25_golden_int16_test_data_cc",
        "generated_strided_slice25_input0_int16_test_data_cc",
        "generated_strided_slice25_model_data_cc",
        "generated_strided_slice26_golden_int16_test_data_cc",
        "generated_strided_slice26_input0_int16_test_data_cc",
        "generated_strided_slice26_model_data_cc",
        "generated_strided_slice27_golden_int16_test_data_cc",
        "generated_strided_slice27_input0_int16_test_data_cc",
        "generated_strided_slice27_model_data_cc",
        "generated_strided_slice28_golden_int16_test_data_cc",
        "generated_strided_slice28_input0_int16_test_data_cc",
        "generated_strided_slice28_model_data_cc",
        "generated_strided_slice29_golden_int16_test_data_cc",
        "generated_strided_slice29_input0_int16_test_data_cc",
        "generated_strided_slice29_model_data_cc",
        "generated_strided_slice2_golden_int16_test_data_cc",
        "generated_strided_slice2_input0_int16_test_data_cc",
        "generated_strided_slice2_model_data_cc",
        "generated_strided_slice30_golden_int16_test_data_cc",
        "generated_strided_slice30_input0_int16_test_data_cc",
        "generated_strided_slice30_model_data_cc",
        "generated_strided_slice31_golden_int16_test_data_cc",
        "generated_strided_slice31_input0_int16_test_data_cc",
        "generated_strided_slice31_model_data_cc",
        "generated_strided_slice32_golden_int16_test_data_cc",
        "generated_strided_slice32_input0_int16_test_data_cc",
        "generated_strided_slice32_model_data_cc",
        "generated_strided_slice33_golden_int16_test_data_cc",
        "generated_strided_slice33_input0_int16_test_data_cc",
        "generated_strided_slice33_model_data_cc",
        "generated_strided_slice3_golden_int16_test_data_cc",
        "generated_strided_slice3_input0_int16_test_data_cc",
        "generated_strided_slice3_model_data_cc",
        "generated_strided_slice4_golden_int16_test_data_cc",
        "generated_strided_slice4_input0_int16_test_data_cc",
        "generated_strided_slice4_model_data_cc",
        "generated_strided_slice5_golden_int16_test_data_cc",
        "generated_strided_slice5_input0_int16_test_data_cc",
        "generated_strided_slice5_model_data_cc",
        "generated_strided_slice6_golden_int16_test_data_cc",
        "generated_strided_slice6_input0_int16_test_data_cc",
        "generated_strided_slice6_model_data_cc",
        "generated_strided_slice7_golden_int16_test_data_cc",
        "generated_strided_slice7_input0_int16_test_data_cc",
        "generated_strided_slice7_model_data_cc",
        "generated_strided_slice8_golden_int16_test_data_cc",
        "generated_strided_slice8_input0_int16_test_data_cc",
        "generated_strided_slice8_model_data_cc",
        "generated_strided_slice9_golden_int16_test_data_cc",
        "generated_strided_slice9_input0_int16_test_data_cc",
        "generated_strided_slice9_model_data_cc",
    ],
    hdrs = [
        "generated_strided_slice0_golden_int16_test_data_hdr",
        "generated_strided_slice0_input0_int16_test_data_hdr",
        "generated_strided_slice0_model_data_hdr",
        "generated_strided_slice10_golden_int16_test_data_hdr",
        "generated_strided_slice10_input0_int16_test_data_hdr",
        "generated_strided_slice10_model_data_hdr",
        "generated_strided_slice11_golden_int16_test_data_hdr",
        "generated_strided_slice11_input0_int16_test_data_hdr",
        "generated_strided_slice11_model_data_hdr",
        "generated_strided_slice12_golden_int16_test_data_hdr",
        "generated_strided_slice12_input0_int16_test_data_hdr",
        "generated_strided_slice12_model_data_hdr",
        "generated_strided_slice13_golden_int16_test_data_hdr",
        "generated_strided_slice13_input0_int16_test_data_hdr",
        "generated_strided_slice13_model_data_hdr",
        "generated_strided_slice14_golden_int16_test_data_hdr",
        "generated_strided_slice14_input0_int16_test_data_hdr",
        "generated_strided_slice14_model_data_hdr",
        "generated_strided_slice15_golden_int16_test_data_hdr",
        "generated_strided_slice15_input0_int16_test_data_hdr",
        "generated_strided_slice15_model_data_hdr",
        "generated_strided_slice16_golden_int16_test_data_hdr",
        "generated_strided_slice16_input0_int16_test_data_hdr",
        "generated_strided_slice16_model_data_hdr",
        "generated_strided_slice17_golden_int16_test_data_hdr",
        "generated_strided_slice17_input0_int16_test_data_hdr",
        "generated_strided_slice17_model_data_hdr",
        "generated_strided_slice18_golden_int16_test_data_hdr",
        "generated_strided_slice18_input0_int16_test_data_hdr",
        "generated_strided_slice18_model_data_hdr",
        "generated_strided_slice19_golden_int16_test_data_hdr",
        "generated_strided_slice19_input0_int16_test_data_hdr",
        "generated_strided_slice19_model_data_hdr",
        "generated_strided_slice1_golden_int16_test_data_hdr",
        "generated_strided_slice1_input0_int16_test_data_hdr",
        "generated_strided_slice1_model_data_hdr",
        "generated_strided_slice20_golden_int16_test_data_hdr",
        "generated_strided_slice20_input0_int16_test_data_hdr",
        "generated_strided_slice20_model_data_hdr",
        "generated_strided_slice21_golden_int16_test_data_hdr",
        "generated_strided_slice21_input0_int16_test_data_hdr",
        "generated_strided_slice21_model_data_hdr",
        "generated_strided_slice22_golden_int16_test_data_hdr",
        "generated_strided_slice22_input0_int16_test_data_hdr",
        "generated_strided_slice22_model_data_hdr",
        "generated_strided_slice23_golden_int16_test_data_hdr",
        "generated_strided_slice23_input0_int16_test_data_hdr",
        "generated_strided_slice23_model_data_hdr",
        "generated_strided_slice24_golden_int16_test_data_hdr",
        "generated_strided_slice24_input0_int16_test_data_hdr",
        "generated_strided_slice24_model_data_hdr",
        "generated_strided_slice25_golden_int16_test_data_hdr",
        "generated_strided_slice25_input0_int16_test_data_hdr",
        "generated_strided_slice25_model_data_hdr",
        "generated_strided_slice26_golden_int16_test_data_hdr",
        "generated_strided_slice26_input0_int16_test_data_hdr",
        "generated_strided_slice26_model_data_hdr",
        "generated_strided_slice27_golden_int16_test_data_hdr",
        "generated_strided_slice27_input0_int16_test_data_hdr",
        "generated_strided_slice27_model_data_hdr",
        "generated_strided_slice28_golden_int16_test_data_hdr",
        "generated_strided_slice28_input0_int16_test_data_hdr",
        "generated_strided_slice28_model_data_hdr",
        "generated_strided_slice29_golden_int16_test_data_hdr",
        "generated_strided_slice29_input0_int16_test_data_hdr",
        "generated_strided_slice29_model_data_hdr",
        "generated_strided_slice2_golden_int16_test_data_hdr",
        "generated_strided_slice2_input0_int16_test_data_hdr",
        "generated_strided_slice2_model_data_hdr",
        "generated_strided_slice30_golden_int16_test_data_hdr",
        "generated_strided_slice30_input0_int16_test_data_hdr",
        "generated_strided_slice30_model_data_hdr",
        "generated_strided_slice31_golden_int16_test_data_hdr",
        "generated_strided_slice31_input0_int16_test_data_hdr",
        "generated_strided_slice31_model_data_hdr",
        "generated_strided_slice32_golden_int16_test_data_hdr",
        "generated_strided_slice32_input0_int16_test_data_hdr",
        "generated_strided_slice32_model_data_hdr",
        "generated_strided_slice33_golden_int16_test_data_hdr",
        "generated_strided_slice33_input0_int16_test_data_hdr",
        "generated_strided_slice33_model_data_hdr",
        "generated_strided_slice3_golden_int16_test_data_hdr",
        "generated_strided_slice3_input0_int16_test_data_hdr",
        "generated_strided_slice3_model_data_hdr",
        "generated_strided_slice4_golden_int16_test_data_hdr",
        "generated_strided_slice4_input0_int16_test_data_hdr",
        "generated_strided_slice4_model_data_hdr",
        "generated_strided_slice5_golden_int16_test_data_hdr",
        "generated_strided_slice5_input0_int16_test_data_hdr",
        "generated_strided_slice5_model_data_hdr",
        "generated_strided_slice6_golden_int16_test_data_hdr",
        "generated_strided_slice6_input0_int16_test_data_hdr",
        "generated_strided_slice6_model_data_hdr",
        "generated_strided_slice7_golden_int16_test_data_hdr",
        "generated_strided_slice7_input0_int16_test_data_hdr",
        "generated_strided_slice7_model_data_hdr",
        "generated_strided_slice8_golden_int16_test_data_hdr",
        "generated_strided_slice8_input0_int16_test_data_hdr",
        "generated_strided_slice8_model_data_hdr",
        "generated_strided_slice9_golden_int16_test_data_hdr",
        "generated_strided_slice9_input0_int16_test_data_hdr",
        "generated_strided_slice9_model_data_hdr",
    ],
)

tflm_cc_test(
    name = "integration_test",
    srcs = [
        "integration_tests.cc",
    ],
    deps = [
        ":models_and_testdata",
        "//python/tflite_micro:python_ops_resolver",
        "//tensorflow/lite/micro:micro_framework",
        "//tensorflow/lite/micro:micro_log",
        "//tensorflow/lite/micro:micro_resource_variable",
        "//tensorflow/lite/micro:op_resolvers",
        "//tensorflow/lite/micro:recording_allocators",
        "//tensorflow/lite/micro/testing:micro_test",
    ],
)
