# tflm_runtime is deprecated, please use runtime instead.
# TODO(b/286456378): remove once all usage is changed to the runtime target.
py_library(
    name = "tflm_runtime",
    srcs = ["tflm_runtime.py"],
    visibility = ["//visibility:public"],
    deps = ["//python/tflite_micro:runtime"],
)
