# Description:
#   generated integration test for one specific kernel in a model.
load(
    "//tensorflow/lite/micro:build_def.bzl",
    "generate_cc_arrays",
    "tflm_cc_library",
    "tflm_cc_test",
)

package(
    default_visibility = ["//visibility:public"],
    # Disabling layering_check because of http://b/177257332
    features = ["-layering_check"],
    licenses = ["notice"],
)

generate_cc_arrays(
    name = "generated_pad0_model_data_cc",
    src = "pad0.tflite",
    out = "pad0_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad0_model_data_hdr",
    src = "pad0.tflite",
    out = "pad0_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad1_model_data_cc",
    src = "pad1.tflite",
    out = "pad1_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad1_model_data_hdr",
    src = "pad1.tflite",
    out = "pad1_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad2_model_data_cc",
    src = "pad2.tflite",
    out = "pad2_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad2_model_data_hdr",
    src = "pad2.tflite",
    out = "pad2_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad3_model_data_cc",
    src = "pad3.tflite",
    out = "pad3_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad3_model_data_hdr",
    src = "pad3.tflite",
    out = "pad3_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad4_model_data_cc",
    src = "pad4.tflite",
    out = "pad4_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad4_model_data_hdr",
    src = "pad4.tflite",
    out = "pad4_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad5_model_data_cc",
    src = "pad5.tflite",
    out = "pad5_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad5_model_data_hdr",
    src = "pad5.tflite",
    out = "pad5_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad6_model_data_cc",
    src = "pad6.tflite",
    out = "pad6_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad6_model_data_hdr",
    src = "pad6.tflite",
    out = "pad6_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad7_model_data_cc",
    src = "pad7.tflite",
    out = "pad7_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad7_model_data_hdr",
    src = "pad7.tflite",
    out = "pad7_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad8_model_data_cc",
    src = "pad8.tflite",
    out = "pad8_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad8_model_data_hdr",
    src = "pad8.tflite",
    out = "pad8_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad9_model_data_cc",
    src = "pad9.tflite",
    out = "pad9_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad9_model_data_hdr",
    src = "pad9.tflite",
    out = "pad9_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad10_model_data_cc",
    src = "pad10.tflite",
    out = "pad10_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad10_model_data_hdr",
    src = "pad10.tflite",
    out = "pad10_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad11_model_data_cc",
    src = "pad11.tflite",
    out = "pad11_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad11_model_data_hdr",
    src = "pad11.tflite",
    out = "pad11_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad12_model_data_cc",
    src = "pad12.tflite",
    out = "pad12_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad12_model_data_hdr",
    src = "pad12.tflite",
    out = "pad12_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad13_model_data_cc",
    src = "pad13.tflite",
    out = "pad13_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad13_model_data_hdr",
    src = "pad13.tflite",
    out = "pad13_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad14_model_data_cc",
    src = "pad14.tflite",
    out = "pad14_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad14_model_data_hdr",
    src = "pad14.tflite",
    out = "pad14_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad15_model_data_cc",
    src = "pad15.tflite",
    out = "pad15_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad15_model_data_hdr",
    src = "pad15.tflite",
    out = "pad15_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad16_model_data_cc",
    src = "pad16.tflite",
    out = "pad16_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad16_model_data_hdr",
    src = "pad16.tflite",
    out = "pad16_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad17_model_data_cc",
    src = "pad17.tflite",
    out = "pad17_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad17_model_data_hdr",
    src = "pad17.tflite",
    out = "pad17_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad18_model_data_cc",
    src = "pad18.tflite",
    out = "pad18_model_data.cc",
)

generate_cc_arrays(
    name = "generated_pad18_model_data_hdr",
    src = "pad18.tflite",
    out = "pad18_model_data.h",
)

generate_cc_arrays(
    name = "generated_pad0_input0_int16_test_data_cc",
    src = "pad0_input0_int16.csv",
    out = "pad0_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad0_input0_int16_test_data_hdr",
    src = "pad0_input0_int16.csv",
    out = "pad0_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad0_golden_int16_test_data_cc",
    src = "pad0_golden_int16.csv",
    out = "pad0_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad0_golden_int16_test_data_hdr",
    src = "pad0_golden_int16.csv",
    out = "pad0_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad1_input0_int16_test_data_cc",
    src = "pad1_input0_int16.csv",
    out = "pad1_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad1_input0_int16_test_data_hdr",
    src = "pad1_input0_int16.csv",
    out = "pad1_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad1_golden_int16_test_data_cc",
    src = "pad1_golden_int16.csv",
    out = "pad1_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad1_golden_int16_test_data_hdr",
    src = "pad1_golden_int16.csv",
    out = "pad1_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad2_input0_int16_test_data_cc",
    src = "pad2_input0_int16.csv",
    out = "pad2_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad2_input0_int16_test_data_hdr",
    src = "pad2_input0_int16.csv",
    out = "pad2_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad2_golden_int16_test_data_cc",
    src = "pad2_golden_int16.csv",
    out = "pad2_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad2_golden_int16_test_data_hdr",
    src = "pad2_golden_int16.csv",
    out = "pad2_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad3_input0_int16_test_data_cc",
    src = "pad3_input0_int16.csv",
    out = "pad3_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad3_input0_int16_test_data_hdr",
    src = "pad3_input0_int16.csv",
    out = "pad3_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad3_golden_int16_test_data_cc",
    src = "pad3_golden_int16.csv",
    out = "pad3_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad3_golden_int16_test_data_hdr",
    src = "pad3_golden_int16.csv",
    out = "pad3_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad4_input0_int16_test_data_cc",
    src = "pad4_input0_int16.csv",
    out = "pad4_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad4_input0_int16_test_data_hdr",
    src = "pad4_input0_int16.csv",
    out = "pad4_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad4_golden_int16_test_data_cc",
    src = "pad4_golden_int16.csv",
    out = "pad4_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad4_golden_int16_test_data_hdr",
    src = "pad4_golden_int16.csv",
    out = "pad4_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad5_input0_int16_test_data_cc",
    src = "pad5_input0_int16.csv",
    out = "pad5_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad5_input0_int16_test_data_hdr",
    src = "pad5_input0_int16.csv",
    out = "pad5_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad5_golden_int16_test_data_cc",
    src = "pad5_golden_int16.csv",
    out = "pad5_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad5_golden_int16_test_data_hdr",
    src = "pad5_golden_int16.csv",
    out = "pad5_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad6_input0_int16_test_data_cc",
    src = "pad6_input0_int16.csv",
    out = "pad6_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad6_input0_int16_test_data_hdr",
    src = "pad6_input0_int16.csv",
    out = "pad6_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad6_golden_int16_test_data_cc",
    src = "pad6_golden_int16.csv",
    out = "pad6_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad6_golden_int16_test_data_hdr",
    src = "pad6_golden_int16.csv",
    out = "pad6_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad7_input0_int16_test_data_cc",
    src = "pad7_input0_int16.csv",
    out = "pad7_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad7_input0_int16_test_data_hdr",
    src = "pad7_input0_int16.csv",
    out = "pad7_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad7_golden_int16_test_data_cc",
    src = "pad7_golden_int16.csv",
    out = "pad7_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad7_golden_int16_test_data_hdr",
    src = "pad7_golden_int16.csv",
    out = "pad7_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad8_input0_int16_test_data_cc",
    src = "pad8_input0_int16.csv",
    out = "pad8_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad8_input0_int16_test_data_hdr",
    src = "pad8_input0_int16.csv",
    out = "pad8_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad8_golden_int16_test_data_cc",
    src = "pad8_golden_int16.csv",
    out = "pad8_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad8_golden_int16_test_data_hdr",
    src = "pad8_golden_int16.csv",
    out = "pad8_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad9_input0_int16_test_data_cc",
    src = "pad9_input0_int16.csv",
    out = "pad9_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad9_input0_int16_test_data_hdr",
    src = "pad9_input0_int16.csv",
    out = "pad9_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad9_golden_int16_test_data_cc",
    src = "pad9_golden_int16.csv",
    out = "pad9_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad9_golden_int16_test_data_hdr",
    src = "pad9_golden_int16.csv",
    out = "pad9_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad10_input0_int16_test_data_cc",
    src = "pad10_input0_int16.csv",
    out = "pad10_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad10_input0_int16_test_data_hdr",
    src = "pad10_input0_int16.csv",
    out = "pad10_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad10_golden_int16_test_data_cc",
    src = "pad10_golden_int16.csv",
    out = "pad10_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad10_golden_int16_test_data_hdr",
    src = "pad10_golden_int16.csv",
    out = "pad10_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad11_input0_int16_test_data_cc",
    src = "pad11_input0_int16.csv",
    out = "pad11_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad11_input0_int16_test_data_hdr",
    src = "pad11_input0_int16.csv",
    out = "pad11_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad11_golden_int16_test_data_cc",
    src = "pad11_golden_int16.csv",
    out = "pad11_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad11_golden_int16_test_data_hdr",
    src = "pad11_golden_int16.csv",
    out = "pad11_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad12_input0_int16_test_data_cc",
    src = "pad12_input0_int16.csv",
    out = "pad12_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad12_input0_int16_test_data_hdr",
    src = "pad12_input0_int16.csv",
    out = "pad12_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad12_golden_int16_test_data_cc",
    src = "pad12_golden_int16.csv",
    out = "pad12_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad12_golden_int16_test_data_hdr",
    src = "pad12_golden_int16.csv",
    out = "pad12_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad13_input0_int16_test_data_cc",
    src = "pad13_input0_int16.csv",
    out = "pad13_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad13_input0_int16_test_data_hdr",
    src = "pad13_input0_int16.csv",
    out = "pad13_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad13_golden_int16_test_data_cc",
    src = "pad13_golden_int16.csv",
    out = "pad13_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad13_golden_int16_test_data_hdr",
    src = "pad13_golden_int16.csv",
    out = "pad13_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad14_input0_int16_test_data_cc",
    src = "pad14_input0_int16.csv",
    out = "pad14_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad14_input0_int16_test_data_hdr",
    src = "pad14_input0_int16.csv",
    out = "pad14_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad14_golden_int16_test_data_cc",
    src = "pad14_golden_int16.csv",
    out = "pad14_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad14_golden_int16_test_data_hdr",
    src = "pad14_golden_int16.csv",
    out = "pad14_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad15_input0_int16_test_data_cc",
    src = "pad15_input0_int16.csv",
    out = "pad15_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad15_input0_int16_test_data_hdr",
    src = "pad15_input0_int16.csv",
    out = "pad15_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad15_golden_int16_test_data_cc",
    src = "pad15_golden_int16.csv",
    out = "pad15_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad15_golden_int16_test_data_hdr",
    src = "pad15_golden_int16.csv",
    out = "pad15_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad16_input0_int16_test_data_cc",
    src = "pad16_input0_int16.csv",
    out = "pad16_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad16_input0_int16_test_data_hdr",
    src = "pad16_input0_int16.csv",
    out = "pad16_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad16_golden_int16_test_data_cc",
    src = "pad16_golden_int16.csv",
    out = "pad16_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad16_golden_int16_test_data_hdr",
    src = "pad16_golden_int16.csv",
    out = "pad16_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad17_input0_int16_test_data_cc",
    src = "pad17_input0_int16.csv",
    out = "pad17_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad17_input0_int16_test_data_hdr",
    src = "pad17_input0_int16.csv",
    out = "pad17_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad17_golden_int16_test_data_cc",
    src = "pad17_golden_int16.csv",
    out = "pad17_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad17_golden_int16_test_data_hdr",
    src = "pad17_golden_int16.csv",
    out = "pad17_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad18_input0_int16_test_data_cc",
    src = "pad18_input0_int16.csv",
    out = "pad18_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad18_input0_int16_test_data_hdr",
    src = "pad18_input0_int16.csv",
    out = "pad18_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_pad18_golden_int16_test_data_cc",
    src = "pad18_golden_int16.csv",
    out = "pad18_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_pad18_golden_int16_test_data_hdr",
    src = "pad18_golden_int16.csv",
    out = "pad18_golden_int16_test_data.h",
)

tflm_cc_library(
    name = "models_and_testdata",
    srcs = [
        "generated_pad0_golden_int16_test_data_cc",
        "generated_pad0_input0_int16_test_data_cc",
        "generated_pad0_model_data_cc",
        "generated_pad10_golden_int16_test_data_cc",
        "generated_pad10_input0_int16_test_data_cc",
        "generated_pad10_model_data_cc",
        "generated_pad11_golden_int16_test_data_cc",
        "generated_pad11_input0_int16_test_data_cc",
        "generated_pad11_model_data_cc",
        "generated_pad12_golden_int16_test_data_cc",
        "generated_pad12_input0_int16_test_data_cc",
        "generated_pad12_model_data_cc",
        "generated_pad13_golden_int16_test_data_cc",
        "generated_pad13_input0_int16_test_data_cc",
        "generated_pad13_model_data_cc",
        "generated_pad14_golden_int16_test_data_cc",
        "generated_pad14_input0_int16_test_data_cc",
        "generated_pad14_model_data_cc",
        "generated_pad15_golden_int16_test_data_cc",
        "generated_pad15_input0_int16_test_data_cc",
        "generated_pad15_model_data_cc",
        "generated_pad16_golden_int16_test_data_cc",
        "generated_pad16_input0_int16_test_data_cc",
        "generated_pad16_model_data_cc",
        "generated_pad17_golden_int16_test_data_cc",
        "generated_pad17_input0_int16_test_data_cc",
        "generated_pad17_model_data_cc",
        "generated_pad18_golden_int16_test_data_cc",
        "generated_pad18_input0_int16_test_data_cc",
        "generated_pad18_model_data_cc",
        "generated_pad1_golden_int16_test_data_cc",
        "generated_pad1_input0_int16_test_data_cc",
        "generated_pad1_model_data_cc",
        "generated_pad2_golden_int16_test_data_cc",
        "generated_pad2_input0_int16_test_data_cc",
        "generated_pad2_model_data_cc",
        "generated_pad3_golden_int16_test_data_cc",
        "generated_pad3_input0_int16_test_data_cc",
        "generated_pad3_model_data_cc",
        "generated_pad4_golden_int16_test_data_cc",
        "generated_pad4_input0_int16_test_data_cc",
        "generated_pad4_model_data_cc",
        "generated_pad5_golden_int16_test_data_cc",
        "generated_pad5_input0_int16_test_data_cc",
        "generated_pad5_model_data_cc",
        "generated_pad6_golden_int16_test_data_cc",
        "generated_pad6_input0_int16_test_data_cc",
        "generated_pad6_model_data_cc",
        "generated_pad7_golden_int16_test_data_cc",
        "generated_pad7_input0_int16_test_data_cc",
        "generated_pad7_model_data_cc",
        "generated_pad8_golden_int16_test_data_cc",
        "generated_pad8_input0_int16_test_data_cc",
        "generated_pad8_model_data_cc",
        "generated_pad9_golden_int16_test_data_cc",
        "generated_pad9_input0_int16_test_data_cc",
        "generated_pad9_model_data_cc",
    ],
    hdrs = [
        "generated_pad0_golden_int16_test_data_hdr",
        "generated_pad0_input0_int16_test_data_hdr",
        "generated_pad0_model_data_hdr",
        "generated_pad10_golden_int16_test_data_hdr",
        "generated_pad10_input0_int16_test_data_hdr",
        "generated_pad10_model_data_hdr",
        "generated_pad11_golden_int16_test_data_hdr",
        "generated_pad11_input0_int16_test_data_hdr",
        "generated_pad11_model_data_hdr",
        "generated_pad12_golden_int16_test_data_hdr",
        "generated_pad12_input0_int16_test_data_hdr",
        "generated_pad12_model_data_hdr",
        "generated_pad13_golden_int16_test_data_hdr",
        "generated_pad13_input0_int16_test_data_hdr",
        "generated_pad13_model_data_hdr",
        "generated_pad14_golden_int16_test_data_hdr",
        "generated_pad14_input0_int16_test_data_hdr",
        "generated_pad14_model_data_hdr",
        "generated_pad15_golden_int16_test_data_hdr",
        "generated_pad15_input0_int16_test_data_hdr",
        "generated_pad15_model_data_hdr",
        "generated_pad16_golden_int16_test_data_hdr",
        "generated_pad16_input0_int16_test_data_hdr",
        "generated_pad16_model_data_hdr",
        "generated_pad17_golden_int16_test_data_hdr",
        "generated_pad17_input0_int16_test_data_hdr",
        "generated_pad17_model_data_hdr",
        "generated_pad18_golden_int16_test_data_hdr",
        "generated_pad18_input0_int16_test_data_hdr",
        "generated_pad18_model_data_hdr",
        "generated_pad1_golden_int16_test_data_hdr",
        "generated_pad1_input0_int16_test_data_hdr",
        "generated_pad1_model_data_hdr",
        "generated_pad2_golden_int16_test_data_hdr",
        "generated_pad2_input0_int16_test_data_hdr",
        "generated_pad2_model_data_hdr",
        "generated_pad3_golden_int16_test_data_hdr",
        "generated_pad3_input0_int16_test_data_hdr",
        "generated_pad3_model_data_hdr",
        "generated_pad4_golden_int16_test_data_hdr",
        "generated_pad4_input0_int16_test_data_hdr",
        "generated_pad4_model_data_hdr",
        "generated_pad5_golden_int16_test_data_hdr",
        "generated_pad5_input0_int16_test_data_hdr",
        "generated_pad5_model_data_hdr",
        "generated_pad6_golden_int16_test_data_hdr",
        "generated_pad6_input0_int16_test_data_hdr",
        "generated_pad6_model_data_hdr",
        "generated_pad7_golden_int16_test_data_hdr",
        "generated_pad7_input0_int16_test_data_hdr",
        "generated_pad7_model_data_hdr",
        "generated_pad8_golden_int16_test_data_hdr",
        "generated_pad8_input0_int16_test_data_hdr",
        "generated_pad8_model_data_hdr",
        "generated_pad9_golden_int16_test_data_hdr",
        "generated_pad9_input0_int16_test_data_hdr",
        "generated_pad9_model_data_hdr",
    ],
)

tflm_cc_test(
    name = "integration_test",
    srcs = [
        "integration_tests.cc",
    ],
    deps = [
        ":models_and_testdata",
        "//python/tflite_micro:python_ops_resolver",
        "//tensorflow/lite/micro:micro_framework",
        "//tensorflow/lite/micro:micro_log",
        "//tensorflow/lite/micro:micro_resource_variable",
        "//tensorflow/lite/micro:op_resolvers",
        "//tensorflow/lite/micro:recording_allocators",
        "//tensorflow/lite/micro/testing:micro_test",
    ],
)
