cc_test(
    name = "cc_deps_link_test",
    size = "small",
    srcs = [
        "cc_deps_link_test.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@tensorflow_cc_deps//:cc_library",
    ],
)
