# Description:
#   generated integration test for one specific kernel in a model.
load(
    "//tensorflow/lite/micro:build_def.bzl",
    "generate_cc_arrays",
    "tflm_cc_library",
    "tflm_cc_test",
)

package(
    default_visibility = ["//visibility:public"],
    # Disabling layering_check because of http://b/177257332
    features = ["-layering_check"],
    licenses = ["notice"],
)

generate_cc_arrays(
    name = "generated_add0_model_data_cc",
    src = "add0.tflite",
    out = "add0_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add0_model_data_hdr",
    src = "add0.tflite",
    out = "add0_model_data.h",
)

generate_cc_arrays(
    name = "generated_add1_model_data_cc",
    src = "add1.tflite",
    out = "add1_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add1_model_data_hdr",
    src = "add1.tflite",
    out = "add1_model_data.h",
)

generate_cc_arrays(
    name = "generated_add2_model_data_cc",
    src = "add2.tflite",
    out = "add2_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add2_model_data_hdr",
    src = "add2.tflite",
    out = "add2_model_data.h",
)

generate_cc_arrays(
    name = "generated_add3_model_data_cc",
    src = "add3.tflite",
    out = "add3_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add3_model_data_hdr",
    src = "add3.tflite",
    out = "add3_model_data.h",
)

generate_cc_arrays(
    name = "generated_add4_model_data_cc",
    src = "add4.tflite",
    out = "add4_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add4_model_data_hdr",
    src = "add4.tflite",
    out = "add4_model_data.h",
)

generate_cc_arrays(
    name = "generated_add5_model_data_cc",
    src = "add5.tflite",
    out = "add5_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add5_model_data_hdr",
    src = "add5.tflite",
    out = "add5_model_data.h",
)

generate_cc_arrays(
    name = "generated_add6_model_data_cc",
    src = "add6.tflite",
    out = "add6_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add6_model_data_hdr",
    src = "add6.tflite",
    out = "add6_model_data.h",
)

generate_cc_arrays(
    name = "generated_add7_model_data_cc",
    src = "add7.tflite",
    out = "add7_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add7_model_data_hdr",
    src = "add7.tflite",
    out = "add7_model_data.h",
)

generate_cc_arrays(
    name = "generated_add8_model_data_cc",
    src = "add8.tflite",
    out = "add8_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add8_model_data_hdr",
    src = "add8.tflite",
    out = "add8_model_data.h",
)

generate_cc_arrays(
    name = "generated_add9_model_data_cc",
    src = "add9.tflite",
    out = "add9_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add9_model_data_hdr",
    src = "add9.tflite",
    out = "add9_model_data.h",
)

generate_cc_arrays(
    name = "generated_add10_model_data_cc",
    src = "add10.tflite",
    out = "add10_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add10_model_data_hdr",
    src = "add10.tflite",
    out = "add10_model_data.h",
)

generate_cc_arrays(
    name = "generated_add11_model_data_cc",
    src = "add11.tflite",
    out = "add11_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add11_model_data_hdr",
    src = "add11.tflite",
    out = "add11_model_data.h",
)

generate_cc_arrays(
    name = "generated_add12_model_data_cc",
    src = "add12.tflite",
    out = "add12_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add12_model_data_hdr",
    src = "add12.tflite",
    out = "add12_model_data.h",
)

generate_cc_arrays(
    name = "generated_add13_model_data_cc",
    src = "add13.tflite",
    out = "add13_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add13_model_data_hdr",
    src = "add13.tflite",
    out = "add13_model_data.h",
)

generate_cc_arrays(
    name = "generated_add14_model_data_cc",
    src = "add14.tflite",
    out = "add14_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add14_model_data_hdr",
    src = "add14.tflite",
    out = "add14_model_data.h",
)

generate_cc_arrays(
    name = "generated_add15_model_data_cc",
    src = "add15.tflite",
    out = "add15_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add15_model_data_hdr",
    src = "add15.tflite",
    out = "add15_model_data.h",
)

generate_cc_arrays(
    name = "generated_add16_model_data_cc",
    src = "add16.tflite",
    out = "add16_model_data.cc",
)

generate_cc_arrays(
    name = "generated_add16_model_data_hdr",
    src = "add16.tflite",
    out = "add16_model_data.h",
)

generate_cc_arrays(
    name = "generated_add0_input0_int16_test_data_cc",
    src = "add0_input0_int16.csv",
    out = "add0_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add0_input0_int16_test_data_hdr",
    src = "add0_input0_int16.csv",
    out = "add0_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add0_input1_int16_test_data_cc",
    src = "add0_input1_int16.csv",
    out = "add0_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add0_input1_int16_test_data_hdr",
    src = "add0_input1_int16.csv",
    out = "add0_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add0_golden_int16_test_data_cc",
    src = "add0_golden_int16.csv",
    out = "add0_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add0_golden_int16_test_data_hdr",
    src = "add0_golden_int16.csv",
    out = "add0_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add1_input0_int16_test_data_cc",
    src = "add1_input0_int16.csv",
    out = "add1_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add1_input0_int16_test_data_hdr",
    src = "add1_input0_int16.csv",
    out = "add1_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add1_input1_int16_test_data_cc",
    src = "add1_input1_int16.csv",
    out = "add1_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add1_input1_int16_test_data_hdr",
    src = "add1_input1_int16.csv",
    out = "add1_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add1_golden_int16_test_data_cc",
    src = "add1_golden_int16.csv",
    out = "add1_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add1_golden_int16_test_data_hdr",
    src = "add1_golden_int16.csv",
    out = "add1_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add2_input0_int16_test_data_cc",
    src = "add2_input0_int16.csv",
    out = "add2_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add2_input0_int16_test_data_hdr",
    src = "add2_input0_int16.csv",
    out = "add2_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add2_input1_int16_test_data_cc",
    src = "add2_input1_int16.csv",
    out = "add2_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add2_input1_int16_test_data_hdr",
    src = "add2_input1_int16.csv",
    out = "add2_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add2_golden_int16_test_data_cc",
    src = "add2_golden_int16.csv",
    out = "add2_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add2_golden_int16_test_data_hdr",
    src = "add2_golden_int16.csv",
    out = "add2_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add3_input0_int16_test_data_cc",
    src = "add3_input0_int16.csv",
    out = "add3_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add3_input0_int16_test_data_hdr",
    src = "add3_input0_int16.csv",
    out = "add3_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add3_input1_int16_test_data_cc",
    src = "add3_input1_int16.csv",
    out = "add3_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add3_input1_int16_test_data_hdr",
    src = "add3_input1_int16.csv",
    out = "add3_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add3_golden_int16_test_data_cc",
    src = "add3_golden_int16.csv",
    out = "add3_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add3_golden_int16_test_data_hdr",
    src = "add3_golden_int16.csv",
    out = "add3_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add4_input0_int16_test_data_cc",
    src = "add4_input0_int16.csv",
    out = "add4_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add4_input0_int16_test_data_hdr",
    src = "add4_input0_int16.csv",
    out = "add4_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add4_input1_int16_test_data_cc",
    src = "add4_input1_int16.csv",
    out = "add4_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add4_input1_int16_test_data_hdr",
    src = "add4_input1_int16.csv",
    out = "add4_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add4_golden_int16_test_data_cc",
    src = "add4_golden_int16.csv",
    out = "add4_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add4_golden_int16_test_data_hdr",
    src = "add4_golden_int16.csv",
    out = "add4_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add5_input0_int16_test_data_cc",
    src = "add5_input0_int16.csv",
    out = "add5_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add5_input0_int16_test_data_hdr",
    src = "add5_input0_int16.csv",
    out = "add5_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add5_input1_int16_test_data_cc",
    src = "add5_input1_int16.csv",
    out = "add5_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add5_input1_int16_test_data_hdr",
    src = "add5_input1_int16.csv",
    out = "add5_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add5_golden_int16_test_data_cc",
    src = "add5_golden_int16.csv",
    out = "add5_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add5_golden_int16_test_data_hdr",
    src = "add5_golden_int16.csv",
    out = "add5_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add6_input0_int16_test_data_cc",
    src = "add6_input0_int16.csv",
    out = "add6_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add6_input0_int16_test_data_hdr",
    src = "add6_input0_int16.csv",
    out = "add6_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add6_input1_int16_test_data_cc",
    src = "add6_input1_int16.csv",
    out = "add6_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add6_input1_int16_test_data_hdr",
    src = "add6_input1_int16.csv",
    out = "add6_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add6_golden_int16_test_data_cc",
    src = "add6_golden_int16.csv",
    out = "add6_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add6_golden_int16_test_data_hdr",
    src = "add6_golden_int16.csv",
    out = "add6_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add7_input0_int16_test_data_cc",
    src = "add7_input0_int16.csv",
    out = "add7_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add7_input0_int16_test_data_hdr",
    src = "add7_input0_int16.csv",
    out = "add7_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add7_input1_int16_test_data_cc",
    src = "add7_input1_int16.csv",
    out = "add7_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add7_input1_int16_test_data_hdr",
    src = "add7_input1_int16.csv",
    out = "add7_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add7_golden_int16_test_data_cc",
    src = "add7_golden_int16.csv",
    out = "add7_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add7_golden_int16_test_data_hdr",
    src = "add7_golden_int16.csv",
    out = "add7_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add8_input0_int16_test_data_cc",
    src = "add8_input0_int16.csv",
    out = "add8_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add8_input0_int16_test_data_hdr",
    src = "add8_input0_int16.csv",
    out = "add8_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add8_input1_int16_test_data_cc",
    src = "add8_input1_int16.csv",
    out = "add8_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add8_input1_int16_test_data_hdr",
    src = "add8_input1_int16.csv",
    out = "add8_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add8_golden_int16_test_data_cc",
    src = "add8_golden_int16.csv",
    out = "add8_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add8_golden_int16_test_data_hdr",
    src = "add8_golden_int16.csv",
    out = "add8_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add9_input0_int16_test_data_cc",
    src = "add9_input0_int16.csv",
    out = "add9_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add9_input0_int16_test_data_hdr",
    src = "add9_input0_int16.csv",
    out = "add9_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add9_input1_int16_test_data_cc",
    src = "add9_input1_int16.csv",
    out = "add9_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add9_input1_int16_test_data_hdr",
    src = "add9_input1_int16.csv",
    out = "add9_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add9_golden_int16_test_data_cc",
    src = "add9_golden_int16.csv",
    out = "add9_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add9_golden_int16_test_data_hdr",
    src = "add9_golden_int16.csv",
    out = "add9_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add10_input0_int16_test_data_cc",
    src = "add10_input0_int16.csv",
    out = "add10_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add10_input0_int16_test_data_hdr",
    src = "add10_input0_int16.csv",
    out = "add10_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add10_input1_int16_test_data_cc",
    src = "add10_input1_int16.csv",
    out = "add10_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add10_input1_int16_test_data_hdr",
    src = "add10_input1_int16.csv",
    out = "add10_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add10_golden_int16_test_data_cc",
    src = "add10_golden_int16.csv",
    out = "add10_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add10_golden_int16_test_data_hdr",
    src = "add10_golden_int16.csv",
    out = "add10_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add11_input0_int16_test_data_cc",
    src = "add11_input0_int16.csv",
    out = "add11_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add11_input0_int16_test_data_hdr",
    src = "add11_input0_int16.csv",
    out = "add11_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add11_input1_int16_test_data_cc",
    src = "add11_input1_int16.csv",
    out = "add11_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add11_input1_int16_test_data_hdr",
    src = "add11_input1_int16.csv",
    out = "add11_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add11_golden_int16_test_data_cc",
    src = "add11_golden_int16.csv",
    out = "add11_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add11_golden_int16_test_data_hdr",
    src = "add11_golden_int16.csv",
    out = "add11_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add12_input0_int16_test_data_cc",
    src = "add12_input0_int16.csv",
    out = "add12_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add12_input0_int16_test_data_hdr",
    src = "add12_input0_int16.csv",
    out = "add12_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add12_input1_int16_test_data_cc",
    src = "add12_input1_int16.csv",
    out = "add12_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add12_input1_int16_test_data_hdr",
    src = "add12_input1_int16.csv",
    out = "add12_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add12_golden_int16_test_data_cc",
    src = "add12_golden_int16.csv",
    out = "add12_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add12_golden_int16_test_data_hdr",
    src = "add12_golden_int16.csv",
    out = "add12_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add13_input0_int16_test_data_cc",
    src = "add13_input0_int16.csv",
    out = "add13_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add13_input0_int16_test_data_hdr",
    src = "add13_input0_int16.csv",
    out = "add13_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add13_input1_int16_test_data_cc",
    src = "add13_input1_int16.csv",
    out = "add13_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add13_input1_int16_test_data_hdr",
    src = "add13_input1_int16.csv",
    out = "add13_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add13_golden_int16_test_data_cc",
    src = "add13_golden_int16.csv",
    out = "add13_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add13_golden_int16_test_data_hdr",
    src = "add13_golden_int16.csv",
    out = "add13_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add14_input0_int16_test_data_cc",
    src = "add14_input0_int16.csv",
    out = "add14_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add14_input0_int16_test_data_hdr",
    src = "add14_input0_int16.csv",
    out = "add14_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add14_input1_int16_test_data_cc",
    src = "add14_input1_int16.csv",
    out = "add14_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add14_input1_int16_test_data_hdr",
    src = "add14_input1_int16.csv",
    out = "add14_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add14_golden_int16_test_data_cc",
    src = "add14_golden_int16.csv",
    out = "add14_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add14_golden_int16_test_data_hdr",
    src = "add14_golden_int16.csv",
    out = "add14_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add15_input0_int16_test_data_cc",
    src = "add15_input0_int16.csv",
    out = "add15_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add15_input0_int16_test_data_hdr",
    src = "add15_input0_int16.csv",
    out = "add15_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add15_input1_int16_test_data_cc",
    src = "add15_input1_int16.csv",
    out = "add15_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add15_input1_int16_test_data_hdr",
    src = "add15_input1_int16.csv",
    out = "add15_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add15_golden_int16_test_data_cc",
    src = "add15_golden_int16.csv",
    out = "add15_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add15_golden_int16_test_data_hdr",
    src = "add15_golden_int16.csv",
    out = "add15_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add16_input0_int16_test_data_cc",
    src = "add16_input0_int16.csv",
    out = "add16_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add16_input0_int16_test_data_hdr",
    src = "add16_input0_int16.csv",
    out = "add16_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add16_input1_int16_test_data_cc",
    src = "add16_input1_int16.csv",
    out = "add16_input1_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add16_input1_int16_test_data_hdr",
    src = "add16_input1_int16.csv",
    out = "add16_input1_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_add16_golden_int16_test_data_cc",
    src = "add16_golden_int16.csv",
    out = "add16_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_add16_golden_int16_test_data_hdr",
    src = "add16_golden_int16.csv",
    out = "add16_golden_int16_test_data.h",
)

tflm_cc_library(
    name = "models_and_testdata",
    srcs = [
        "generated_add0_golden_int16_test_data_cc",
        "generated_add0_input0_int16_test_data_cc",
        "generated_add0_input1_int16_test_data_cc",
        "generated_add0_model_data_cc",
        "generated_add10_golden_int16_test_data_cc",
        "generated_add10_input0_int16_test_data_cc",
        "generated_add10_input1_int16_test_data_cc",
        "generated_add10_model_data_cc",
        "generated_add11_golden_int16_test_data_cc",
        "generated_add11_input0_int16_test_data_cc",
        "generated_add11_input1_int16_test_data_cc",
        "generated_add11_model_data_cc",
        "generated_add12_golden_int16_test_data_cc",
        "generated_add12_input0_int16_test_data_cc",
        "generated_add12_input1_int16_test_data_cc",
        "generated_add12_model_data_cc",
        "generated_add13_golden_int16_test_data_cc",
        "generated_add13_input0_int16_test_data_cc",
        "generated_add13_input1_int16_test_data_cc",
        "generated_add13_model_data_cc",
        "generated_add14_golden_int16_test_data_cc",
        "generated_add14_input0_int16_test_data_cc",
        "generated_add14_input1_int16_test_data_cc",
        "generated_add14_model_data_cc",
        "generated_add15_golden_int16_test_data_cc",
        "generated_add15_input0_int16_test_data_cc",
        "generated_add15_input1_int16_test_data_cc",
        "generated_add15_model_data_cc",
        "generated_add16_golden_int16_test_data_cc",
        "generated_add16_input0_int16_test_data_cc",
        "generated_add16_input1_int16_test_data_cc",
        "generated_add16_model_data_cc",
        "generated_add1_golden_int16_test_data_cc",
        "generated_add1_input0_int16_test_data_cc",
        "generated_add1_input1_int16_test_data_cc",
        "generated_add1_model_data_cc",
        "generated_add2_golden_int16_test_data_cc",
        "generated_add2_input0_int16_test_data_cc",
        "generated_add2_input1_int16_test_data_cc",
        "generated_add2_model_data_cc",
        "generated_add3_golden_int16_test_data_cc",
        "generated_add3_input0_int16_test_data_cc",
        "generated_add3_input1_int16_test_data_cc",
        "generated_add3_model_data_cc",
        "generated_add4_golden_int16_test_data_cc",
        "generated_add4_input0_int16_test_data_cc",
        "generated_add4_input1_int16_test_data_cc",
        "generated_add4_model_data_cc",
        "generated_add5_golden_int16_test_data_cc",
        "generated_add5_input0_int16_test_data_cc",
        "generated_add5_input1_int16_test_data_cc",
        "generated_add5_model_data_cc",
        "generated_add6_golden_int16_test_data_cc",
        "generated_add6_input0_int16_test_data_cc",
        "generated_add6_input1_int16_test_data_cc",
        "generated_add6_model_data_cc",
        "generated_add7_golden_int16_test_data_cc",
        "generated_add7_input0_int16_test_data_cc",
        "generated_add7_input1_int16_test_data_cc",
        "generated_add7_model_data_cc",
        "generated_add8_golden_int16_test_data_cc",
        "generated_add8_input0_int16_test_data_cc",
        "generated_add8_input1_int16_test_data_cc",
        "generated_add8_model_data_cc",
        "generated_add9_golden_int16_test_data_cc",
        "generated_add9_input0_int16_test_data_cc",
        "generated_add9_input1_int16_test_data_cc",
        "generated_add9_model_data_cc",
    ],
    hdrs = [
        "generated_add0_golden_int16_test_data_hdr",
        "generated_add0_input0_int16_test_data_hdr",
        "generated_add0_input1_int16_test_data_hdr",
        "generated_add0_model_data_hdr",
        "generated_add10_golden_int16_test_data_hdr",
        "generated_add10_input0_int16_test_data_hdr",
        "generated_add10_input1_int16_test_data_hdr",
        "generated_add10_model_data_hdr",
        "generated_add11_golden_int16_test_data_hdr",
        "generated_add11_input0_int16_test_data_hdr",
        "generated_add11_input1_int16_test_data_hdr",
        "generated_add11_model_data_hdr",
        "generated_add12_golden_int16_test_data_hdr",
        "generated_add12_input0_int16_test_data_hdr",
        "generated_add12_input1_int16_test_data_hdr",
        "generated_add12_model_data_hdr",
        "generated_add13_golden_int16_test_data_hdr",
        "generated_add13_input0_int16_test_data_hdr",
        "generated_add13_input1_int16_test_data_hdr",
        "generated_add13_model_data_hdr",
        "generated_add14_golden_int16_test_data_hdr",
        "generated_add14_input0_int16_test_data_hdr",
        "generated_add14_input1_int16_test_data_hdr",
        "generated_add14_model_data_hdr",
        "generated_add15_golden_int16_test_data_hdr",
        "generated_add15_input0_int16_test_data_hdr",
        "generated_add15_input1_int16_test_data_hdr",
        "generated_add15_model_data_hdr",
        "generated_add16_golden_int16_test_data_hdr",
        "generated_add16_input0_int16_test_data_hdr",
        "generated_add16_input1_int16_test_data_hdr",
        "generated_add16_model_data_hdr",
        "generated_add1_golden_int16_test_data_hdr",
        "generated_add1_input0_int16_test_data_hdr",
        "generated_add1_input1_int16_test_data_hdr",
        "generated_add1_model_data_hdr",
        "generated_add2_golden_int16_test_data_hdr",
        "generated_add2_input0_int16_test_data_hdr",
        "generated_add2_input1_int16_test_data_hdr",
        "generated_add2_model_data_hdr",
        "generated_add3_golden_int16_test_data_hdr",
        "generated_add3_input0_int16_test_data_hdr",
        "generated_add3_input1_int16_test_data_hdr",
        "generated_add3_model_data_hdr",
        "generated_add4_golden_int16_test_data_hdr",
        "generated_add4_input0_int16_test_data_hdr",
        "generated_add4_input1_int16_test_data_hdr",
        "generated_add4_model_data_hdr",
        "generated_add5_golden_int16_test_data_hdr",
        "generated_add5_input0_int16_test_data_hdr",
        "generated_add5_input1_int16_test_data_hdr",
        "generated_add5_model_data_hdr",
        "generated_add6_golden_int16_test_data_hdr",
        "generated_add6_input0_int16_test_data_hdr",
        "generated_add6_input1_int16_test_data_hdr",
        "generated_add6_model_data_hdr",
        "generated_add7_golden_int16_test_data_hdr",
        "generated_add7_input0_int16_test_data_hdr",
        "generated_add7_input1_int16_test_data_hdr",
        "generated_add7_model_data_hdr",
        "generated_add8_golden_int16_test_data_hdr",
        "generated_add8_input0_int16_test_data_hdr",
        "generated_add8_input1_int16_test_data_hdr",
        "generated_add8_model_data_hdr",
        "generated_add9_golden_int16_test_data_hdr",
        "generated_add9_input0_int16_test_data_hdr",
        "generated_add9_input1_int16_test_data_hdr",
        "generated_add9_model_data_hdr",
    ],
)

tflm_cc_test(
    name = "integration_test",
    srcs = [
        "integration_tests.cc",
    ],
    deps = [
        ":models_and_testdata",
        "//python/tflite_micro:python_ops_resolver",
        "//tensorflow/lite/micro:micro_framework",
        "//tensorflow/lite/micro:micro_log",
        "//tensorflow/lite/micro:micro_resource_variable",
        "//tensorflow/lite/micro:op_resolvers",
        "//tensorflow/lite/micro:recording_allocators",
        "//tensorflow/lite/micro/testing:micro_test",
    ],
)
