# Test data for signal tests. This is used to store large arrays which would make tests less readable.

package(
    default_visibility = ["//signal/micro/kernels:__subpackages__"],
    licenses = ["notice"],
)

cc_library(
    name = "fft_test_data",
    srcs = [
        "fft_test_data.cc",
    ],
    hdrs = [
        "fft_test_data.h",
    ],
)
