# Description:
#   generated integration test for one specific kernel in a model.
load(
    "//tensorflow/lite/micro:build_def.bzl",
    "generate_cc_arrays",
    "tflm_cc_library",
    "tflm_cc_test",
)

package(
    default_visibility = ["//visibility:public"],
    # Disabling layering_check because of http://b/177257332
    features = ["-layering_check"],
    licenses = ["notice"],
)

generate_cc_arrays(
    name = "generated_leaky_relu0_model_data_cc",
    src = "leaky_relu0.tflite",
    out = "leaky_relu0_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu0_model_data_hdr",
    src = "leaky_relu0.tflite",
    out = "leaky_relu0_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu1_model_data_cc",
    src = "leaky_relu1.tflite",
    out = "leaky_relu1_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu1_model_data_hdr",
    src = "leaky_relu1.tflite",
    out = "leaky_relu1_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu2_model_data_cc",
    src = "leaky_relu2.tflite",
    out = "leaky_relu2_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu2_model_data_hdr",
    src = "leaky_relu2.tflite",
    out = "leaky_relu2_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu3_model_data_cc",
    src = "leaky_relu3.tflite",
    out = "leaky_relu3_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu3_model_data_hdr",
    src = "leaky_relu3.tflite",
    out = "leaky_relu3_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu4_model_data_cc",
    src = "leaky_relu4.tflite",
    out = "leaky_relu4_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu4_model_data_hdr",
    src = "leaky_relu4.tflite",
    out = "leaky_relu4_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu5_model_data_cc",
    src = "leaky_relu5.tflite",
    out = "leaky_relu5_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu5_model_data_hdr",
    src = "leaky_relu5.tflite",
    out = "leaky_relu5_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu6_model_data_cc",
    src = "leaky_relu6.tflite",
    out = "leaky_relu6_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu6_model_data_hdr",
    src = "leaky_relu6.tflite",
    out = "leaky_relu6_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu7_model_data_cc",
    src = "leaky_relu7.tflite",
    out = "leaky_relu7_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu7_model_data_hdr",
    src = "leaky_relu7.tflite",
    out = "leaky_relu7_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu8_model_data_cc",
    src = "leaky_relu8.tflite",
    out = "leaky_relu8_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu8_model_data_hdr",
    src = "leaky_relu8.tflite",
    out = "leaky_relu8_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu9_model_data_cc",
    src = "leaky_relu9.tflite",
    out = "leaky_relu9_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu9_model_data_hdr",
    src = "leaky_relu9.tflite",
    out = "leaky_relu9_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu10_model_data_cc",
    src = "leaky_relu10.tflite",
    out = "leaky_relu10_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu10_model_data_hdr",
    src = "leaky_relu10.tflite",
    out = "leaky_relu10_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu11_model_data_cc",
    src = "leaky_relu11.tflite",
    out = "leaky_relu11_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu11_model_data_hdr",
    src = "leaky_relu11.tflite",
    out = "leaky_relu11_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu12_model_data_cc",
    src = "leaky_relu12.tflite",
    out = "leaky_relu12_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu12_model_data_hdr",
    src = "leaky_relu12.tflite",
    out = "leaky_relu12_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu13_model_data_cc",
    src = "leaky_relu13.tflite",
    out = "leaky_relu13_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu13_model_data_hdr",
    src = "leaky_relu13.tflite",
    out = "leaky_relu13_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu14_model_data_cc",
    src = "leaky_relu14.tflite",
    out = "leaky_relu14_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu14_model_data_hdr",
    src = "leaky_relu14.tflite",
    out = "leaky_relu14_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu15_model_data_cc",
    src = "leaky_relu15.tflite",
    out = "leaky_relu15_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu15_model_data_hdr",
    src = "leaky_relu15.tflite",
    out = "leaky_relu15_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu16_model_data_cc",
    src = "leaky_relu16.tflite",
    out = "leaky_relu16_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu16_model_data_hdr",
    src = "leaky_relu16.tflite",
    out = "leaky_relu16_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu17_model_data_cc",
    src = "leaky_relu17.tflite",
    out = "leaky_relu17_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu17_model_data_hdr",
    src = "leaky_relu17.tflite",
    out = "leaky_relu17_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu18_model_data_cc",
    src = "leaky_relu18.tflite",
    out = "leaky_relu18_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu18_model_data_hdr",
    src = "leaky_relu18.tflite",
    out = "leaky_relu18_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu19_model_data_cc",
    src = "leaky_relu19.tflite",
    out = "leaky_relu19_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu19_model_data_hdr",
    src = "leaky_relu19.tflite",
    out = "leaky_relu19_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu20_model_data_cc",
    src = "leaky_relu20.tflite",
    out = "leaky_relu20_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu20_model_data_hdr",
    src = "leaky_relu20.tflite",
    out = "leaky_relu20_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu21_model_data_cc",
    src = "leaky_relu21.tflite",
    out = "leaky_relu21_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu21_model_data_hdr",
    src = "leaky_relu21.tflite",
    out = "leaky_relu21_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu22_model_data_cc",
    src = "leaky_relu22.tflite",
    out = "leaky_relu22_model_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu22_model_data_hdr",
    src = "leaky_relu22.tflite",
    out = "leaky_relu22_model_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu0_input0_int16_test_data_cc",
    src = "leaky_relu0_input0_int16.csv",
    out = "leaky_relu0_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu0_input0_int16_test_data_hdr",
    src = "leaky_relu0_input0_int16.csv",
    out = "leaky_relu0_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu0_golden_int16_test_data_cc",
    src = "leaky_relu0_golden_int16.csv",
    out = "leaky_relu0_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu0_golden_int16_test_data_hdr",
    src = "leaky_relu0_golden_int16.csv",
    out = "leaky_relu0_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu1_input0_int16_test_data_cc",
    src = "leaky_relu1_input0_int16.csv",
    out = "leaky_relu1_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu1_input0_int16_test_data_hdr",
    src = "leaky_relu1_input0_int16.csv",
    out = "leaky_relu1_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu1_golden_int16_test_data_cc",
    src = "leaky_relu1_golden_int16.csv",
    out = "leaky_relu1_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu1_golden_int16_test_data_hdr",
    src = "leaky_relu1_golden_int16.csv",
    out = "leaky_relu1_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu2_input0_int16_test_data_cc",
    src = "leaky_relu2_input0_int16.csv",
    out = "leaky_relu2_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu2_input0_int16_test_data_hdr",
    src = "leaky_relu2_input0_int16.csv",
    out = "leaky_relu2_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu2_golden_int16_test_data_cc",
    src = "leaky_relu2_golden_int16.csv",
    out = "leaky_relu2_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu2_golden_int16_test_data_hdr",
    src = "leaky_relu2_golden_int16.csv",
    out = "leaky_relu2_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu3_input0_int16_test_data_cc",
    src = "leaky_relu3_input0_int16.csv",
    out = "leaky_relu3_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu3_input0_int16_test_data_hdr",
    src = "leaky_relu3_input0_int16.csv",
    out = "leaky_relu3_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu3_golden_int16_test_data_cc",
    src = "leaky_relu3_golden_int16.csv",
    out = "leaky_relu3_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu3_golden_int16_test_data_hdr",
    src = "leaky_relu3_golden_int16.csv",
    out = "leaky_relu3_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu4_input0_int16_test_data_cc",
    src = "leaky_relu4_input0_int16.csv",
    out = "leaky_relu4_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu4_input0_int16_test_data_hdr",
    src = "leaky_relu4_input0_int16.csv",
    out = "leaky_relu4_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu4_golden_int16_test_data_cc",
    src = "leaky_relu4_golden_int16.csv",
    out = "leaky_relu4_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu4_golden_int16_test_data_hdr",
    src = "leaky_relu4_golden_int16.csv",
    out = "leaky_relu4_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu5_input0_int16_test_data_cc",
    src = "leaky_relu5_input0_int16.csv",
    out = "leaky_relu5_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu5_input0_int16_test_data_hdr",
    src = "leaky_relu5_input0_int16.csv",
    out = "leaky_relu5_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu5_golden_int16_test_data_cc",
    src = "leaky_relu5_golden_int16.csv",
    out = "leaky_relu5_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu5_golden_int16_test_data_hdr",
    src = "leaky_relu5_golden_int16.csv",
    out = "leaky_relu5_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu6_input0_int16_test_data_cc",
    src = "leaky_relu6_input0_int16.csv",
    out = "leaky_relu6_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu6_input0_int16_test_data_hdr",
    src = "leaky_relu6_input0_int16.csv",
    out = "leaky_relu6_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu6_golden_int16_test_data_cc",
    src = "leaky_relu6_golden_int16.csv",
    out = "leaky_relu6_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu6_golden_int16_test_data_hdr",
    src = "leaky_relu6_golden_int16.csv",
    out = "leaky_relu6_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu7_input0_int16_test_data_cc",
    src = "leaky_relu7_input0_int16.csv",
    out = "leaky_relu7_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu7_input0_int16_test_data_hdr",
    src = "leaky_relu7_input0_int16.csv",
    out = "leaky_relu7_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu7_golden_int16_test_data_cc",
    src = "leaky_relu7_golden_int16.csv",
    out = "leaky_relu7_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu7_golden_int16_test_data_hdr",
    src = "leaky_relu7_golden_int16.csv",
    out = "leaky_relu7_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu8_input0_int16_test_data_cc",
    src = "leaky_relu8_input0_int16.csv",
    out = "leaky_relu8_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu8_input0_int16_test_data_hdr",
    src = "leaky_relu8_input0_int16.csv",
    out = "leaky_relu8_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu8_golden_int16_test_data_cc",
    src = "leaky_relu8_golden_int16.csv",
    out = "leaky_relu8_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu8_golden_int16_test_data_hdr",
    src = "leaky_relu8_golden_int16.csv",
    out = "leaky_relu8_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu9_input0_int16_test_data_cc",
    src = "leaky_relu9_input0_int16.csv",
    out = "leaky_relu9_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu9_input0_int16_test_data_hdr",
    src = "leaky_relu9_input0_int16.csv",
    out = "leaky_relu9_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu9_golden_int16_test_data_cc",
    src = "leaky_relu9_golden_int16.csv",
    out = "leaky_relu9_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu9_golden_int16_test_data_hdr",
    src = "leaky_relu9_golden_int16.csv",
    out = "leaky_relu9_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu10_input0_int16_test_data_cc",
    src = "leaky_relu10_input0_int16.csv",
    out = "leaky_relu10_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu10_input0_int16_test_data_hdr",
    src = "leaky_relu10_input0_int16.csv",
    out = "leaky_relu10_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu10_golden_int16_test_data_cc",
    src = "leaky_relu10_golden_int16.csv",
    out = "leaky_relu10_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu10_golden_int16_test_data_hdr",
    src = "leaky_relu10_golden_int16.csv",
    out = "leaky_relu10_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu11_input0_int16_test_data_cc",
    src = "leaky_relu11_input0_int16.csv",
    out = "leaky_relu11_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu11_input0_int16_test_data_hdr",
    src = "leaky_relu11_input0_int16.csv",
    out = "leaky_relu11_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu11_golden_int16_test_data_cc",
    src = "leaky_relu11_golden_int16.csv",
    out = "leaky_relu11_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu11_golden_int16_test_data_hdr",
    src = "leaky_relu11_golden_int16.csv",
    out = "leaky_relu11_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu12_input0_int16_test_data_cc",
    src = "leaky_relu12_input0_int16.csv",
    out = "leaky_relu12_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu12_input0_int16_test_data_hdr",
    src = "leaky_relu12_input0_int16.csv",
    out = "leaky_relu12_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu12_golden_int16_test_data_cc",
    src = "leaky_relu12_golden_int16.csv",
    out = "leaky_relu12_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu12_golden_int16_test_data_hdr",
    src = "leaky_relu12_golden_int16.csv",
    out = "leaky_relu12_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu13_input0_int16_test_data_cc",
    src = "leaky_relu13_input0_int16.csv",
    out = "leaky_relu13_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu13_input0_int16_test_data_hdr",
    src = "leaky_relu13_input0_int16.csv",
    out = "leaky_relu13_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu13_golden_int16_test_data_cc",
    src = "leaky_relu13_golden_int16.csv",
    out = "leaky_relu13_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu13_golden_int16_test_data_hdr",
    src = "leaky_relu13_golden_int16.csv",
    out = "leaky_relu13_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu14_input0_int16_test_data_cc",
    src = "leaky_relu14_input0_int16.csv",
    out = "leaky_relu14_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu14_input0_int16_test_data_hdr",
    src = "leaky_relu14_input0_int16.csv",
    out = "leaky_relu14_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu14_golden_int16_test_data_cc",
    src = "leaky_relu14_golden_int16.csv",
    out = "leaky_relu14_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu14_golden_int16_test_data_hdr",
    src = "leaky_relu14_golden_int16.csv",
    out = "leaky_relu14_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu15_input0_int16_test_data_cc",
    src = "leaky_relu15_input0_int16.csv",
    out = "leaky_relu15_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu15_input0_int16_test_data_hdr",
    src = "leaky_relu15_input0_int16.csv",
    out = "leaky_relu15_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu15_golden_int16_test_data_cc",
    src = "leaky_relu15_golden_int16.csv",
    out = "leaky_relu15_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu15_golden_int16_test_data_hdr",
    src = "leaky_relu15_golden_int16.csv",
    out = "leaky_relu15_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu16_input0_int16_test_data_cc",
    src = "leaky_relu16_input0_int16.csv",
    out = "leaky_relu16_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu16_input0_int16_test_data_hdr",
    src = "leaky_relu16_input0_int16.csv",
    out = "leaky_relu16_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu16_golden_int16_test_data_cc",
    src = "leaky_relu16_golden_int16.csv",
    out = "leaky_relu16_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu16_golden_int16_test_data_hdr",
    src = "leaky_relu16_golden_int16.csv",
    out = "leaky_relu16_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu17_input0_int16_test_data_cc",
    src = "leaky_relu17_input0_int16.csv",
    out = "leaky_relu17_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu17_input0_int16_test_data_hdr",
    src = "leaky_relu17_input0_int16.csv",
    out = "leaky_relu17_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu17_golden_int16_test_data_cc",
    src = "leaky_relu17_golden_int16.csv",
    out = "leaky_relu17_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu17_golden_int16_test_data_hdr",
    src = "leaky_relu17_golden_int16.csv",
    out = "leaky_relu17_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu18_input0_int16_test_data_cc",
    src = "leaky_relu18_input0_int16.csv",
    out = "leaky_relu18_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu18_input0_int16_test_data_hdr",
    src = "leaky_relu18_input0_int16.csv",
    out = "leaky_relu18_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu18_golden_int16_test_data_cc",
    src = "leaky_relu18_golden_int16.csv",
    out = "leaky_relu18_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu18_golden_int16_test_data_hdr",
    src = "leaky_relu18_golden_int16.csv",
    out = "leaky_relu18_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu19_input0_int16_test_data_cc",
    src = "leaky_relu19_input0_int16.csv",
    out = "leaky_relu19_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu19_input0_int16_test_data_hdr",
    src = "leaky_relu19_input0_int16.csv",
    out = "leaky_relu19_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu19_golden_int16_test_data_cc",
    src = "leaky_relu19_golden_int16.csv",
    out = "leaky_relu19_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu19_golden_int16_test_data_hdr",
    src = "leaky_relu19_golden_int16.csv",
    out = "leaky_relu19_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu20_input0_int16_test_data_cc",
    src = "leaky_relu20_input0_int16.csv",
    out = "leaky_relu20_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu20_input0_int16_test_data_hdr",
    src = "leaky_relu20_input0_int16.csv",
    out = "leaky_relu20_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu20_golden_int16_test_data_cc",
    src = "leaky_relu20_golden_int16.csv",
    out = "leaky_relu20_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu20_golden_int16_test_data_hdr",
    src = "leaky_relu20_golden_int16.csv",
    out = "leaky_relu20_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu21_input0_int16_test_data_cc",
    src = "leaky_relu21_input0_int16.csv",
    out = "leaky_relu21_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu21_input0_int16_test_data_hdr",
    src = "leaky_relu21_input0_int16.csv",
    out = "leaky_relu21_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu21_golden_int16_test_data_cc",
    src = "leaky_relu21_golden_int16.csv",
    out = "leaky_relu21_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu21_golden_int16_test_data_hdr",
    src = "leaky_relu21_golden_int16.csv",
    out = "leaky_relu21_golden_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu22_input0_int16_test_data_cc",
    src = "leaky_relu22_input0_int16.csv",
    out = "leaky_relu22_input0_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu22_input0_int16_test_data_hdr",
    src = "leaky_relu22_input0_int16.csv",
    out = "leaky_relu22_input0_int16_test_data.h",
)

generate_cc_arrays(
    name = "generated_leaky_relu22_golden_int16_test_data_cc",
    src = "leaky_relu22_golden_int16.csv",
    out = "leaky_relu22_golden_int16_test_data.cc",
)

generate_cc_arrays(
    name = "generated_leaky_relu22_golden_int16_test_data_hdr",
    src = "leaky_relu22_golden_int16.csv",
    out = "leaky_relu22_golden_int16_test_data.h",
)

tflm_cc_library(
    name = "models_and_testdata",
    srcs = [
        "generated_leaky_relu0_golden_int16_test_data_cc",
        "generated_leaky_relu0_input0_int16_test_data_cc",
        "generated_leaky_relu0_model_data_cc",
        "generated_leaky_relu10_golden_int16_test_data_cc",
        "generated_leaky_relu10_input0_int16_test_data_cc",
        "generated_leaky_relu10_model_data_cc",
        "generated_leaky_relu11_golden_int16_test_data_cc",
        "generated_leaky_relu11_input0_int16_test_data_cc",
        "generated_leaky_relu11_model_data_cc",
        "generated_leaky_relu12_golden_int16_test_data_cc",
        "generated_leaky_relu12_input0_int16_test_data_cc",
        "generated_leaky_relu12_model_data_cc",
        "generated_leaky_relu13_golden_int16_test_data_cc",
        "generated_leaky_relu13_input0_int16_test_data_cc",
        "generated_leaky_relu13_model_data_cc",
        "generated_leaky_relu14_golden_int16_test_data_cc",
        "generated_leaky_relu14_input0_int16_test_data_cc",
        "generated_leaky_relu14_model_data_cc",
        "generated_leaky_relu15_golden_int16_test_data_cc",
        "generated_leaky_relu15_input0_int16_test_data_cc",
        "generated_leaky_relu15_model_data_cc",
        "generated_leaky_relu16_golden_int16_test_data_cc",
        "generated_leaky_relu16_input0_int16_test_data_cc",
        "generated_leaky_relu16_model_data_cc",
        "generated_leaky_relu17_golden_int16_test_data_cc",
        "generated_leaky_relu17_input0_int16_test_data_cc",
        "generated_leaky_relu17_model_data_cc",
        "generated_leaky_relu18_golden_int16_test_data_cc",
        "generated_leaky_relu18_input0_int16_test_data_cc",
        "generated_leaky_relu18_model_data_cc",
        "generated_leaky_relu19_golden_int16_test_data_cc",
        "generated_leaky_relu19_input0_int16_test_data_cc",
        "generated_leaky_relu19_model_data_cc",
        "generated_leaky_relu1_golden_int16_test_data_cc",
        "generated_leaky_relu1_input0_int16_test_data_cc",
        "generated_leaky_relu1_model_data_cc",
        "generated_leaky_relu20_golden_int16_test_data_cc",
        "generated_leaky_relu20_input0_int16_test_data_cc",
        "generated_leaky_relu20_model_data_cc",
        "generated_leaky_relu21_golden_int16_test_data_cc",
        "generated_leaky_relu21_input0_int16_test_data_cc",
        "generated_leaky_relu21_model_data_cc",
        "generated_leaky_relu22_golden_int16_test_data_cc",
        "generated_leaky_relu22_input0_int16_test_data_cc",
        "generated_leaky_relu22_model_data_cc",
        "generated_leaky_relu2_golden_int16_test_data_cc",
        "generated_leaky_relu2_input0_int16_test_data_cc",
        "generated_leaky_relu2_model_data_cc",
        "generated_leaky_relu3_golden_int16_test_data_cc",
        "generated_leaky_relu3_input0_int16_test_data_cc",
        "generated_leaky_relu3_model_data_cc",
        "generated_leaky_relu4_golden_int16_test_data_cc",
        "generated_leaky_relu4_input0_int16_test_data_cc",
        "generated_leaky_relu4_model_data_cc",
        "generated_leaky_relu5_golden_int16_test_data_cc",
        "generated_leaky_relu5_input0_int16_test_data_cc",
        "generated_leaky_relu5_model_data_cc",
        "generated_leaky_relu6_golden_int16_test_data_cc",
        "generated_leaky_relu6_input0_int16_test_data_cc",
        "generated_leaky_relu6_model_data_cc",
        "generated_leaky_relu7_golden_int16_test_data_cc",
        "generated_leaky_relu7_input0_int16_test_data_cc",
        "generated_leaky_relu7_model_data_cc",
        "generated_leaky_relu8_golden_int16_test_data_cc",
        "generated_leaky_relu8_input0_int16_test_data_cc",
        "generated_leaky_relu8_model_data_cc",
        "generated_leaky_relu9_golden_int16_test_data_cc",
        "generated_leaky_relu9_input0_int16_test_data_cc",
        "generated_leaky_relu9_model_data_cc",
    ],
    hdrs = [
        "generated_leaky_relu0_golden_int16_test_data_hdr",
        "generated_leaky_relu0_input0_int16_test_data_hdr",
        "generated_leaky_relu0_model_data_hdr",
        "generated_leaky_relu10_golden_int16_test_data_hdr",
        "generated_leaky_relu10_input0_int16_test_data_hdr",
        "generated_leaky_relu10_model_data_hdr",
        "generated_leaky_relu11_golden_int16_test_data_hdr",
        "generated_leaky_relu11_input0_int16_test_data_hdr",
        "generated_leaky_relu11_model_data_hdr",
        "generated_leaky_relu12_golden_int16_test_data_hdr",
        "generated_leaky_relu12_input0_int16_test_data_hdr",
        "generated_leaky_relu12_model_data_hdr",
        "generated_leaky_relu13_golden_int16_test_data_hdr",
        "generated_leaky_relu13_input0_int16_test_data_hdr",
        "generated_leaky_relu13_model_data_hdr",
        "generated_leaky_relu14_golden_int16_test_data_hdr",
        "generated_leaky_relu14_input0_int16_test_data_hdr",
        "generated_leaky_relu14_model_data_hdr",
        "generated_leaky_relu15_golden_int16_test_data_hdr",
        "generated_leaky_relu15_input0_int16_test_data_hdr",
        "generated_leaky_relu15_model_data_hdr",
        "generated_leaky_relu16_golden_int16_test_data_hdr",
        "generated_leaky_relu16_input0_int16_test_data_hdr",
        "generated_leaky_relu16_model_data_hdr",
        "generated_leaky_relu17_golden_int16_test_data_hdr",
        "generated_leaky_relu17_input0_int16_test_data_hdr",
        "generated_leaky_relu17_model_data_hdr",
        "generated_leaky_relu18_golden_int16_test_data_hdr",
        "generated_leaky_relu18_input0_int16_test_data_hdr",
        "generated_leaky_relu18_model_data_hdr",
        "generated_leaky_relu19_golden_int16_test_data_hdr",
        "generated_leaky_relu19_input0_int16_test_data_hdr",
        "generated_leaky_relu19_model_data_hdr",
        "generated_leaky_relu1_golden_int16_test_data_hdr",
        "generated_leaky_relu1_input0_int16_test_data_hdr",
        "generated_leaky_relu1_model_data_hdr",
        "generated_leaky_relu20_golden_int16_test_data_hdr",
        "generated_leaky_relu20_input0_int16_test_data_hdr",
        "generated_leaky_relu20_model_data_hdr",
        "generated_leaky_relu21_golden_int16_test_data_hdr",
        "generated_leaky_relu21_input0_int16_test_data_hdr",
        "generated_leaky_relu21_model_data_hdr",
        "generated_leaky_relu22_golden_int16_test_data_hdr",
        "generated_leaky_relu22_input0_int16_test_data_hdr",
        "generated_leaky_relu22_model_data_hdr",
        "generated_leaky_relu2_golden_int16_test_data_hdr",
        "generated_leaky_relu2_input0_int16_test_data_hdr",
        "generated_leaky_relu2_model_data_hdr",
        "generated_leaky_relu3_golden_int16_test_data_hdr",
        "generated_leaky_relu3_input0_int16_test_data_hdr",
        "generated_leaky_relu3_model_data_hdr",
        "generated_leaky_relu4_golden_int16_test_data_hdr",
        "generated_leaky_relu4_input0_int16_test_data_hdr",
        "generated_leaky_relu4_model_data_hdr",
        "generated_leaky_relu5_golden_int16_test_data_hdr",
        "generated_leaky_relu5_input0_int16_test_data_hdr",
        "generated_leaky_relu5_model_data_hdr",
        "generated_leaky_relu6_golden_int16_test_data_hdr",
        "generated_leaky_relu6_input0_int16_test_data_hdr",
        "generated_leaky_relu6_model_data_hdr",
        "generated_leaky_relu7_golden_int16_test_data_hdr",
        "generated_leaky_relu7_input0_int16_test_data_hdr",
        "generated_leaky_relu7_model_data_hdr",
        "generated_leaky_relu8_golden_int16_test_data_hdr",
        "generated_leaky_relu8_input0_int16_test_data_hdr",
        "generated_leaky_relu8_model_data_hdr",
        "generated_leaky_relu9_golden_int16_test_data_hdr",
        "generated_leaky_relu9_input0_int16_test_data_hdr",
        "generated_leaky_relu9_model_data_hdr",
    ],
)

tflm_cc_test(
    name = "integration_test",
    srcs = [
        "integration_tests.cc",
    ],
    deps = [
        ":models_and_testdata",
        "//python/tflite_micro:python_ops_resolver",
        "//tensorflow/lite/micro:micro_framework",
        "//tensorflow/lite/micro:micro_log",
        "//tensorflow/lite/micro:micro_resource_variable",
        "//tensorflow/lite/micro:op_resolvers",
        "//tensorflow/lite/micro:recording_allocators",
        "//tensorflow/lite/micro/testing:micro_test",
    ],
)
