integration_tests_seanet_leaky_relu_GENERATOR_INPUTS := \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu0.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu1.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu2.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu3.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu4.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu5.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu6.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu7.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu8.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu9.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu10.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu11.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu12.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu13.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu14.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu15.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu16.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu17.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu18.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu19.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu20.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu21.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu22.tflite \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu0_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu0_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu1_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu1_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu2_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu2_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu3_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu3_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu4_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu4_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu5_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu5_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu6_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu6_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu7_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu7_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu8_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu8_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu9_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu9_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu10_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu10_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu11_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu11_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu12_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu12_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu13_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu13_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu14_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu14_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu15_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu15_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu16_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu16_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu17_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu17_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu18_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu18_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu19_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu19_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu20_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu20_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu21_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu21_golden_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu22_input0_int16.csv \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/leaky_relu22_golden_int16.csv \

integration_tests_seanet_leaky_relu_SRCS := \
$(TENSORFLOW_ROOT)tensorflow/lite/micro/integration_tests/seanet/leaky_relu/integration_tests.cc  \
$(TENSORFLOW_ROOT)python/tflite_micro/python_ops_resolver.cc \


integration_tests_seanet_leaky_relu_HDR := \
$(TENSORFLOW_ROOT)python/tflite_micro/python_ops_resolver.h \


$(eval $(call microlite_test,integration_tests_seanet_leaky_relu_test,\
$(integration_tests_seanet_leaky_relu_SRCS),$(integration_tests_seanet_leaky_relu_HDR),$(integration_tests_seanet_leaky_relu_GENERATOR_INPUTS)))