name: Check TfLite Files

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      pr-body:
        required: true
        type: string
    secrets:
      tflm-bot-token:
        required: false

jobs:
  check_tflite_files:
    runs-on: ubuntu-latest
    name: Check PR Modifies TfLite Files
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
        # Do NOT specify ref -> checks out target base branch (main) securely

      - name: Check Files
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ inputs.pr-number }}
          PR_SHA: ${{ inputs.trigger-sha }}
          TFLM_BOT_TOKEN: ${{ secrets.tflm-bot-token || github.token }}
        run: tensorflow/lite/micro/tools/ci_build/check_tflite_files.sh
