name: Test - Windows

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string

jobs:
  bazel:
    runs-on: windows-latest
    timeout-minutes: 60
    name: Windows Bazel
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.trigger-sha }}
          allow-unsafe-pr-checkout: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.13'
      - name: Enable symlinks
        run: git config core.symlinks true
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
        with:
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true
          bazelrc: |
            startup --windows_enable_symlinks
      - name: Select C++ Tests
        shell: bash
        run: |
          # Base: Include everything except //python/...
          echo "//..." > test_patterns.txt
          echo "-//python/..." >> test_patterns.txt
          # Exclude the C++ tests that depend on Python. (Running python targets is really slow)
          bazel query -k --noimplicit_deps '
            let scope = //... in
            kind(cc_test, rdeps($scope, kind("py_(binary|library)", deps($scope))))
          ' 2>/dev/null | sed 's/^/-/' >> test_patterns.txt || true
      - name: Test
        shell: bash
        run: |
          # Test C++ tests only
          bazel --output_user_root="C:/tmp" --windows_enable_symlinks test \
            --config=windows_ci --test_lang_filters=cc --target_pattern_file=test_patterns.txt

  makefile:
    runs-on: windows-latest
    timeout-minutes: 60
    name: Windows Makefile
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.trigger-sha }}
          allow-unsafe-pr-checkout: true
      - uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2
        with:
          msystem: MINGW64
          update: true
          cache: true
          install: >-
            make
            patch
            mingw-w64-x86_64-gcc
            git
            python3
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-pillow
            mingw-w64-x86_64-python-numpy
            mingw-w64-x86_64-python-absl-py
            openssl
            tar
            unzip
            curl
      - name: Test
        shell: msys2 {0}
        run: |
          tensorflow/lite/micro/tools/ci_build/test_x86_default.sh ./
